### ISSUE TITLE
Serialization of objects with null Id crashes.

### ISSUE THREAD

**Issue by rlazar** [jasminb/jsonapi-converter#106]
Commit https://github.com/jasminb/jsonapi-converter/commit/d074a91bc5569ef10e7f8e62f34687f774fb4ad2 introduced a crash when accessing the id of an object that was not populated.
I think it's an extremely common scenario sending to the server an object with null ID in resources creation flows (being server's responsability to generate that ID).

**Comment by jasminb** [comment]
Hey,

Can you describe steps required to reproduce the issue?

**Comment by rlazar** [comment]
Scenario is pretty simple. Having a class like 

```
@Type("objects")
public class ObjectDTO {
    @Id
    private String      id;

    String name;
}
```

In order to create an ObjectDTO resource server side suppose you POST or PUT the serialization of an instance of this class to some /objects collection server side without setting the @Id annotated field - server should assign an ID and return the newly created instance as a result of the POST/PUT operation.

The problem is that when you try to serialize an instance of the ObjectDTO class ResourceConverter will crash due to this line:
`
JsonNode jsonLinks = getResourceLinks(object, attributesNode, id.textValue());
`
because id node is null.

Please let me know if you need more information.

**Comment by pchampau** [comment]
Thanks for fixing this. We hit that problem on 0.6.

**Comment by micheljung** [comment]
Would be lovely if this project made use of Milestones and release bugfixes more often :-) Meanwhile I'll use jitpack.io in order to avoid using the 0.7-SNAPSHOT.

Keep up the good work, I'm very thankful you made this!
