### ISSUE TITLE
Serializing objects

### ISSUE THREAD

**Issue by MrThreepwood** [jasminb/jsonapi-converter#107]
The wiki is rather lengthy, and there's even a section on serializing objects in it with example JSON string outputs, however, no examples of how to actually convert an object to a string. There are also no methods on a ResourceConverter object that returns a string. A more detailed example of this would be useful.

**Comment by jasminb** [comment]
Hey @MrThreepwood,

To create a `String` out of `bytes []`, you can: `new String(byteArray)`.
