### ISSUE TITLE
Unable to map attribute in json API response to a field in the deserialized object

### ISSUE THREAD

**Issue by srividyak** [jasminb/jsonapi-converter#109]
The json API response has 2 attributes:

1. field called "result-provider"
2. another field called "name"

The class that this json gets deserialized to, looks like this:

class Test {
  public String resultProvider;
  public String name;
}

The field "name" gets populated properly in the Test object but not resultProvider. How can we map attributes to whatever fields that we want? I tried tracing the code but not much luck there. Also there seems to be a check where we compare fieldName directly with the attribute that's in the json. Which will not be true in my case because attribute has a hyphen (result-provider) and field in the Test class does not have it.

**Comment by Kevinrob** [comment]
You can use `com.fasterxml.jackson.annotation.JsonProperty` annotation on your field

    @JsonProperty("result-provider")
    public String resultProvider;

**Comment by srividyak** [comment]
@Kevinrob Great! This works. Thanks!
