### ISSUE TITLE
collect annotated fields also from super classes

### ISSUE THREAD

**Issue by fabricehong** [jasminb/jsonapi-converter#11]
what would greatly improve the library's flexibility to be able to define common annotated fields in a superclass.

usefull for ids (and meta if available)

something like that in ReflectionUtils:

```
public static List<Field> getInheritedAnnotatedFields(Class<?> clazz, Class<? extends Annotation> annotation) {
		List<Field> fields = new ArrayList<>();
		Class<?> currentClass = clazz;
		while(currentClass!=null) {
			fields.addAll(getAnnotatedFields(currentClass, annotation));
			currentClass = currentClass.getSuperclass();
		}
		return fields;
	}
}
```

**Comment by bartoslaw** [comment]
+1

**Comment by jasminb** [comment]
Support for inheritance added and pushed to dev, for trying it out, use current SNAPSHOT release from Sonatype snapshot repo (https://oss.sonatype.org/content/repositories/snapshots).
