### ISSUE TITLE
Failed to parse json with included

### ISSUE THREAD

**Issue by elirangoshen** [jasminb/jsonapi-converter#111]
Hi , 
i cannot parse these data i get unknown resource type error...
and i tried to annotate the include data with Relationship..

Can you give an working example how to do it ?

**Comment by jasminb** [comment]
Hello @elirangoshen , did you go trough the README?

In order to use `ResourceConverter', it has to be instantiated using relevant classes:

```
ResourceConverter converter = new ResourceConverter(Book.class, Author.class);
```

**Comment by elirangoshen** [comment]
Yes.. but i'm using these converter with retorift 2 : 

thats my relevant code : 

ObjectMapper objectMapper = new ObjectMapper();

            resourceService = new Retrofit.Builder()
                    .baseUrl(getBaseUrl())
                    .addConverterFactory(new JSONAPIConverterFactory(objectMapper,
                            Chemical.class,
                            AdulticideApplicationRate.class,
                            Equipment.class,
                            Applicator.class,
                            Site.class))
                    .client(getResourceClient())
                    .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                    .build()
                    .create(VDCIResourceService.class);

where should i put the resourceconverter ?

**Comment by jasminb** [comment]
You can use following factory constructor:

```
	public JSONAPIConverterFactory(ResourceConverter converter) {
...
	}
```

This will allow you to enable/disable serialisation/deserialisation options.

**Comment by elirangoshen** [comment]
thats what i did..whats should i enable ? serialisation or deserialisation ?

**Comment by elirangoshen** [comment]
does there is example that parse included that i can see ? 
from what i saw i need to annotate it with relationship , and enable relationship flag in the converter.. but i'd love to see working example

**Comment by jasminb** [comment]
Please take few minutes and go trough the https://github.com/jasminb/jsonapi-converter/blob/develop/README.md.

It has section that shows example with both simple and collection relationships. Another source of information are unit-tests that demonstrate the things you need.

If relationships are named correctly, library should work without any additional settings other than specifying list of classes you are working with (both base and relationship classes).

**Comment by jasminb** [comment]
Hey @elirangoshen, if you managed to resolve your issues please close the issue.
