### ISSUE TITLE
Relationship that is in main data list not connected

### ISSUE THREAD

**Issue by markoilicic** [jasminb/jsonapi-converter#113]
Hi @jasminb,

we have a situation where we don't get a relationship that is already included in the main `data` set.
I'm not sure if I have overlooked something or this is already fixed?

Example:

`{
  "data": [
    {
      "type": "stores",
      "id": "1",
      "attributes": {
        "name": "Name"
      },
      "relationships": {
        "company": {
          "data": {
            "type": "companies",
            "id": "2"
          }
        }
      }
    },
    {
      "type": "companies",
      "id": "2",
      "attributes": {
        "name": "Name"
      }
    }
  ]
}`

As per JsonApi contributor, we should not have duplication of the resources:
https://github.com/json-api/json-api/issues/1144

> The aspect that's often overlooked here is that, if an included resources is present in `data` as a primary resource, then it must not be duplicated in `included`.

Thank you for your support!

Best,
Marko

**Comment by jasminb** [comment]
Hey @markoilicic,

First problem that I see here that there are resources of different type on the same level. Deserialisation content dictates that collection elements must be of the same type.

Now as for resolving relationships, specification says that `included` section is used for this purpose, resources are not dereferenced or should be dereferenced using other resources from the `data` section.

Im not sure what is you relationship with the provider of the API you are consuming, but it appears to be not compliant with the specification or it could be that my understanding of the specification is not correct.

**Comment by markoilicic** [comment]
@jasminb 

I don't think that it's specified that array should not contain different resources types..

Regarding the issue, API team is also using some library for this which is not duplicating relationships if they are already in the main `data` set. As I mentioned in the previous post, this is mentioned by the JsonApi contributor:

> The aspect that's often overlooked here is that, if an included resources is present in data as a primary resource, then it must not be duplicated in `included`.

You can check it on this link: https://github.com/json-api/json-api/issues/1144

**Comment by jasminb** [comment]
Fact that its not explicitly forbidden does not mean that it should be used. I am creating/using APIs for a long time and I have never seen an API that returns collections of random objects.

As for dereferencing relationships, spec says:

```
To reduce the number of HTTP requests, servers MAY allow responses that include related resources along with the requested primary resources. Such responses are called “compound documents”.

In a compound document, all included resources MUST be represented as an array of resource objects in a top-level included member.

Compound documents require “full linkage”, meaning that every included resource MUST be identified by at least one resource identifier object in the same document. These resource identifier objects could either be primary data or represent resource linkage contained within primary or included resources.

The only exception to the full linkage requirement is when relationship fields that would otherwise contain linkage data are excluded via sparse fieldsets.
```

Design decisions made during lib development were driven by specification text and examples provided, as usual, folks are pushing loose specification in the direction they want or direction that makes things easy for them.

Currently, `included` section is parsed and cached first and afterwards, primary resources are parsed and cache is used to dereference resources if possible.

It would not be impossible to implement support for the use-case you provided but it would require two passes trough primary resources, one for deserialising what can be deserialised and another to attempt to dereference resources that could not be dereferenced in first pass.

**Comment by markoilicic** [comment]
Thank you for your response, It's really frustrating how everyone is interpreting documentation differently and different libraries are doing things differently. I will close this issue since I can't argue with you anymore :D
I'll probably have to fork your library and implement this changes since both API's and iOS's libraries are working the same...

Anyway, thank you as always for great library and support!
