### ISSUE TITLE
Unable to retrieve non-JSONAPI JSON objects

### ISSUE THREAD

**Issue by mfeltmann** [jasminb/jsonapi-converter#114]
# Given JSON structure example

```
"data": {
    "type": "persons",
    "id": "some-unique-identifier",
    "attributes": {
        "firstName": "John",
        "lastName": "Doe",
        "contactInformation": [
          {
            "uti": "contact.address.postalAddress",
            "street": "Willy-Brandt-Straße 60",
            "postalCode": "20457",
            "city": "Hamburg",
            "countryCode": "DE"
          },
          {
            "uti": "contact.phoneNumber.landline",
            "phoneNumber": " +49404281310"
          }
        ]
    }
}
```

# Expectation
I'd like to somehow get those contact information into my deserialized model (and back into the serialized JSONAPI as well later) but I cannot.
The preferred type would be a plain simple string holding the whole JSON array.

# Things I've tried already
* Using simple collection classes supported by Jackson. Works well with arrays containing simple data types but not with arrays containing dictionaries.
* Populate some UTI classes to map into is unsuccessful since there is neither identifier nor type to map into those own classes. Its plain json after all.

# Unanswered question
How am I able to mark some specific properties in JSONAPI as to be returned as a plain string value containing all that JSON information?

# Unaccepted answer
> Please use JSONAPI objects in your whole backend.

I don't own this backend. This `uti` stuff prevents backend devs from holding multiple entities which in fact are not entities, so they will not change backend.  
Furthermore JSONAPI itself states:
> Attributes may contain any valid JSON value.

Since any JSON object is a valid JSON value and thus allowed as attribute for this person object.

**Comment by jasminb** [comment]
Hey,

Did you try something like this:

```
	public static class Test {
		private String value;
		private List<Map<String, String>> dicArray;
		
		public String getValue() {
			return value;
		}
		
		public void setValue(String value) {
			this.value = value;
		}
		
		public List<Map<String, String>> getDicArray() {
			return dicArray;
		}
		
		public void setDicArray(List<Map<String, String>> dicArray) {
			this.dicArray = dicArray;
		}
	}
	
	public static void main(String[] args) {
		Test test = new Test();
		test.setValue("value");
		
		test.setDicArray(new ArrayList<>());
		
		Map<String, String> dict = new HashMap<>();
		dict.put("key", "value");
		test.getDicArray().add(dict);
		
		String json = JSONConverter.toJSON(test);
		Test fromJson = JSONConverter.fromJSON(json, Test.class);
		
		System.out.println(json);
		System.out.println(JSONConverter.toJSON(fromJson));
	}
```

**Comment by mfeltmann** [comment]
Didn't use some JSONConverter object right now. Where can I find it?

**Comment by jasminb** [comment]
Hey @mfeltmann, if you change your class to look like this:

```
@Type("persons")
public class Persons {
private String id;
private String firstName;
private java.util.List<Map<String, String>> contactInformation;

// Getters and setters
}
```

It will work with resource converter, `JSONConverter` is not relevant and was used to demonstrate that it is possible to use list of  Map<String, String> as an attribute with jackson.

**Comment by mfeltmann** [comment]
The issue hunted down:

```
"data": {
  "type": "persons",
  "id": "some-unique-identifier",
  "attributes": {
    "firstName": "John",
    "lastName": "Doe",
    "jobs": [
      {
        "uti": "person.job",
        "company": "acme",
        "position": "best guy",
        "category": "everything",
        "contactInformation": [
          {
            "uti": "contact.address.postalAddress",
            "street": "Willy-Brandt-Straße 60",
            "postalCode": "20457",
            "city": "Hamburg",
            "countryCode": "DE"
          },
          {
            "uti": "contact.phoneNumber.landline",
            "phoneNumber": " +49404281310"
          }
        ]
      }
    ]
  }
}
```

This causes the following completely correct exception:

> java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
at [Source: N/A; line: -1, column: -1] (through reference chain: de.rotary.models.dataexchange.PersonDEO["family"]->java.util.ArrayList[0]->java.util.LinkedHashMap["contactInformation"])

However, setting the member to something more abstract like this seemed to do the trick:

```
@JsonProperty("jobs")
private List<Map<String,Object>> jobsJson;
```

Thank you for your time and the enlightenment. 👍
