### ISSUE TITLE
Support Id that is non-string. 

### ISSUE THREAD

**Issue by kennycason** [jasminb/jsonapi-converter#116]
During serialization I noticed the Id has to be String. We have many models where the Ids are integers. Is there any plan to be more flexible with this?

**Comment by jasminb** [comment]
Hey @kennycason,

Specification specifies that the id must be `String`, thats the reason for rigid approach taken. It would be really easy to allow non-string attributes during serialisation but deserialisation becomes a problem where handling would have to be put in place in oder to handle string to target type conversions. I will think about how to make this pluggable so custom converter can be provided during serialisation/deserialisation of id field.

**Comment by kennycason** [comment]
Thanks. Yeah makes sense from a specification standpoint. Unfortunately in practice many ids are integers. Most of the ids I'm currently dealing with are UUIDs fortunately, but there are a few giving me a problem.

**Comment by jasminb** [comment]
Hello @kennycason,

I've added support for non-string resource identifiers in 2a06cc2f6bd5c6efed3f0f3ff2516785bc3474aa. 

`@Id` annotation was extended with optional argument which if provided overrides default identifier handling.
New interface has been provided that needs to be implemented for custom type handling (`ResourceIdHandler`).

Besides providing default `String` handler, lib also provides handlers for `Long` and `Integer` (`LongIdHandler` and `IntegerIdHandler`).

Sample class using `Long` as id:

```java
@Type("long-id-type")
public class LongIdResource {
	
	@Id(LongIdHandler.class)
	private Long id;
// ...
}
```

**Comment by kennycason** [comment]
@jasminb Thanks a lot. This will work perfect. :)

**Comment by kennycason** [comment]
Integrated into my project and confirmed this works like a charm. Thanks again.
