### ISSUE TITLE
How to handle creating resource that doesn't yet have Id.

### ISSUE THREAD

**Issue by kennycason** [jasminb/jsonapi-converter#117]
http://jsonapi.org/format/#crud-creating

I am having problems creating a resource because the resource converter has a hard requirement that ID is present. Is there a way around this? This is important because when creating a resource, no Id exists yet. So far, this seems to be the final road block in allowing me to completely implement this tool into our projects. 

For reference, I created a MessageConverter for Spring that consumes/produces json api spec.

**Comment by jasminb** [comment]
Hey @kennycason, it is possible to disable id requirement during deserialisation:

```
ResourceConverter converter = ...
converter.disableDeserializationOption(DeserializationFeature.REQUIRE_RESOURCE_ID)
```

**Comment by kennycason** [comment]
awesome!! Thanks for the quick response!

**Comment by dulleh** [comment]
Correct me if I'm wrong, but a similar option to disable the requirement for an ID does not exist for serialization. i.e. there is no way currently to convert from a java object that has no ID to json?

**Comment by kennycason** [comment]
@dulleh I would have to check, since I hadn't encountered that case yet. I think the idea is that if a resource is being returned it should have an Id, else it probably isn't really a resource.

**Comment by dulleh** [comment]
@kennycason It's a very similar case to yours: the resource does not exist in the remote DB and we are trying to send a `POST` to have it made but in order to do so need to serialize an object that doesn't have an ID yet (because it doesn't exist yet). Without an ID set the ResourceConverter throws a NullPointer when serializing.

```
Caused by: java.lang.NullPointerException
	at com.github.jasminb.jsonapi.ResourceConverter.getDataNode(ResourceConverter.java:740)
	at com.github.jasminb.jsonapi.ResourceConverter.writeDocument(ResourceConverter.java:631)
```

Currently I'm just setting a temporary ID and stripping it out after serialization but that is un-optimal for obvious reasons.

**Comment by jasminb** [comment]
@dulleh, can you provide a test case that produces the error?

**Comment by dulleh** [comment]
Seems I was a bit off the mark earlier, I didn't notice that it occurs only when you've also set a relationship object. Example below, where the `User` object is a `@Relationship` 

            Status status = new Status();
		//status.setId("id");
		status.setUser(new User());

		byte[] rawData = converter.writeDocument(new JSONAPIDocument<>(status));

This throws the NullPointerException as expected.

In our use case, we are trying to send a request with the body:

    {  
        "data":{  
            "type":"libraryEntries",
            "attributes":{  
                "status":"completed",
                "progress":0,
                "ratingTwenty":0
            },
            "relationships":{  
                "user":{  
                    "data":{  
                        "type":"users",
                        "id":"59163"
                    }
                },
                "anime":{  
                    "data":{  
                        "type":"anime",
                        "id":"22590"
                    }
                }
            }
        }
    }

(sorry for the late reply, I've been busy with exams and only just getting back to coding)
