### ISSUE TITLE
Parse jsonapi requests

### ISSUE THREAD

**Issue by amanique** [jasminb/jsonapi-converter#12]
In the short documentation of this lib, it says that it can be used for "request/response", although i believe, and please correct me if i'm wrong, that it's only for parsing jsonapi responses. Are you planning on implementing request parsing as well? Thanks

**Comment by jasminb** [comment]
Hey,

`ResourceConverter.writeObject(...)` will serialise properly annotated model class into `byte []` which than can be sent as a request.

`Relationship` annotation has `serialise` flag which is used to control relationship serialisation.

**Comment by amanique** [comment]
I'm sorry but when using Retrofit requests like this:

interface services {
  @POST("/endpoint")
  Call<User> getUser(@Body User.Request request);
}

I'm not getting the @Body User.Request class serialized into JSON format using your convertedFactory.
I can do it with JacksonConverterFactory although, but this way i can't parse the User response into jsonapi format using your lib. Is either one or the other.
Can you help please?

**Comment by jasminb** [comment]
Hey again,

Can you please provide full example on how you are creating resource converter and how does your model class looks like. You can omit data that you cannot disclose.

Regards,
Jasmin

**Comment by amanique** [comment]
Hi,

Thanks in advance!
OK, i have a class for making a request in simple json format:

public static class Request implements ServiceCallRequest {

        @JsonProperty("client_id")
        private String client_id = Settings.config.clientId;

        @JsonProperty("client_secret")
        private String client_secret = Settings.config.clientSecret;

        @JsonProperty("grant_type")
        private String grant_type = Authorization.AUTHENTICATION_GRANT;

        @JsonProperty("username")
        private String username;

        @JsonProperty("password")
        private String password;

        public Request() {}

        public Request(String username, String password) {
            this.username = username;
            this.password = password;
        }

        @Override
        public Call getCall() {
            return SmartAppsServices.getService().getAuthorization(this);
        }
    }



Then i instanciate Retrofit in another class:
(I have stripped some sensitive information about endpoints, sorry)


public class SmartAppsServices {

    private static OkHttpClient getOKHttpClient() {
        final OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.setReadTimeout(Settings.REQUEST_TIMEOUT, TimeUnit.SECONDS);
        okHttpClient.setConnectTimeout(Settings.REQUEST_TIMEOUT, TimeUnit.SECONDS);
        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        okHttpClient.interceptors().add(interceptor);
        okHttpClient.interceptors().add(new AuthorizationInterceptor());
        return okHttpClient;
    }

    public interface SmartAppsAPI {

        @POST(USER_REQUEST)
        Call<User> getUser(@Body User.Request userRequest, @Path("id") String id, @QueryMap Map<String,
                String> options);

        @POST(AUTHENTICATION_REQUEST)
        Call<Authorization> getAuthorization(@Body Authorization.Request authorizationRequest);

    }

    public static ObjectMapper objectMapper = new ObjectMapper().configure
            (DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES, false).configure
            (DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);


    private static JacksonConverterFactory jacksonConverterFactory = JacksonConverterFactory.create(objectMapper);
    private static JSONAPIConverterFactory jsonapiConverterFactory = getJsonapiConverterFactory();

    private static JSONAPIConverterFactory getJsonapiConverterFactory() {
        JSONAPIConverterFactory jsonapiConverterFactory = new JSONAPIConverterFactory(objectMapper);
        jsonapiConverterFactory.setAlternativeFactory(jacksonConverterFactory);
        return jsonapiConverterFactory;
    }

    private static final Retrofit RETROFIT_SERVICE = new Retrofit.Builder()
            .client(getOKHttpClient())
            .baseUrl(BASE_URL)
            .addConverterFactory(jsonapiConverterFactory)
            .build();

    private static final SmartAppsAPI SMART_APPS_SERVICES = RETROFIT_SERVICE.create
            (SmartAppsAPI.class);

    public static SmartAppsAPI getService() {
        return SMART_APPS_SERVICES;
    }


The only way to parse my request was setting an alternative converterFactory.
But i have another problem... jsonapi-converter is not compatible with Retrofit 2.0.0, so i have to include an older version.

Thankx again!

**Comment by jasminb** [comment]
Hey,

Your problem is a fact that you are not registering your model class with the `JSONAPIConverterFactory`.

Instead of what you are currently doing, you should:

```
private static JSONAPIConverterFactory getJsonapiConverterFactory() {
    JSONAPIConverterFactory jsonapiConverterFactory = new JSONAPIConverterFactory(objectMapper, YourModelClass.class, AnotherModel.class);
    jsonapiConverterFactory.setAlternativeFactory(jacksonConverterFactory);
    return jsonapiConverterFactory;
}
```

Please read the README.md, it provides all the details on how to write your model classes and annotate them properly.

Regards,
Jasmin

**Comment by amanique** [comment]
I had already tried that, but the app crashes when trying to instantiate Retrofit with a class non jsonapi.
Meaning:

If i do this: 

private static JSONAPIConverterFactory getJsonapiConverterFactory() {
    JSONAPIConverterFactory jsonapiConverterFactory = new JSONAPIConverterFactory(objectMapper, Request.class);
    jsonapiConverterFactory.setAlternativeFactory(jacksonConverterFactory);
    return jsonapiConverterFactory;
}

It crashes.

If i remove jackson and request.class gives me a "no converter exception";

**Comment by jasminb** [comment]
Request class must be annotated with `Type` annotation and it must have an `id` field annotated with `Id` annotation.
