### ISSUE TITLE
Include the converter

### ISSUE THREAD

**Issue by PedBerTor** [jasminb/jsonapi-converter#121]
Hi. My name is Pedro and im doing a hybrid application for university. Im using an api of a page called Kitsu (https://kitsu.io/). The response has json+api format. This is my class:

![captura](https://cloud.githubusercontent.com/assets/16528784/25527118/7d58b48a-2c17-11e7-8d27-7b6403b77cf3.JPG)

As you can see i use all MediaTypes because i do not know how to include only json+api or if even exist json+api option into MediaType. That doesnt matter because it´s work. **My problem is that when i try to get the object, the return is null**. This is the console exit:

[INFO] abr 28, 2017 1:31:09 PM aiss.controller.SearchController doGet
[INFO] DETALLADO: Searching for Kitsu animes of pokemon
[INFO] abr 28, 2017 1:31:09 PM aiss.model.resources.KitsuResource getAnimes
[INFO] DETALLADO: Kitsu URI:https://kitsu.io/api/edge/anime?filter[slug]=pokemon
[INFO] abr 28, 2017 1:31:10 PM org.restlet.engine.connector.HttpClientHelper start
[INFO] INFORMACIÓN: Starting the internal HTTP client
[INFO] abr 28, 2017 1:31:11 PM org.restlet.service.ConverterService toObject
[INFO] ADVERTENCIA: Unable to find a converter for this representation : [application/vnd.api+json]
[INFO] abr 28, 2017 1:31:11 PM aiss.controller.SearchController doGet
[INFO] GRAVE: Kitsu object: null

As you can see: **[INFO] ADVERTENCIA: Unable to find a converter for this representation : [application/vnd.api+json]**

I put these code that i see in your converter documentation into pom.xml:

<dependency>
	<groupId>com.github.jasminb</groupId>
	<artifactId>jsonapi-converter</artifactId>
	<version>0.7</version>
</dependency>

What more i have to do to include the converter into my application? I hope you can help me. Thanks!

**Comment by jasminb** [comment]
Hello Pedro,

In order to use the lib with restlet client, you will need to implement a `Converter` based on the `ResourceConverter` provided by the lib and than register it with the `ClientResource`.

I hope this is helpful for you.

Regards
