### ISSUE TITLE
Throw specific exception when actual type to be used for resource deserialization does not exists

### ISSUE THREAD

**Issue by prawana-perera** [jasminb/jsonapi-converter#131]
Hi, Thanks for this great and simple to use library.

This is more of a feature request than an issue.

**Version** 
0.7

**Context**
We are using this library with our Spring controller to produce and consume JSON-API data from our API clients. We have a specific Spring `HttpMessageConverter` (employing the `ResourceConverter`) to serialise/deserialise `JSONAPIDocument` responses/requests.

Say we have a `@Type("users")` and the client sends a request with the following:
```
{
  "data": {
    "type": "BLAHHHHH",
    "attributes": {
      "name": "Jonh"
....other attributes
    }
  }
}
```
Out `HttpMessageConverter` will use the `ResourceConverter.readDocument`. However since we don't have that type registered the `ResourceConverter` throws a `RuntimeException`. See line 1037.

If this happens we want to present a nice JSON-API error message. We achieve this by having a Spring `ControllerAdvice` handling error and returning `JSONAPIDocument`s with errors.

Currently I am parsing the exception message and if `"No class was registered for type '" + type + "'."` pattern is found customise the error message. Which is a bit ugly.

**Proposed**
Can we make this throw a specific type of RuntimeException so that we can easily trap this and respond to it.

This seems like a simple change and I am happy to provide a PR if you think is a good idea.

Thanks.

**Comment by reecefenwick** [comment]
@prawana-perera I don't suppose you could share how you setup the `HttpMessageConverter.java` to support deserialization of JSONAPIDocument<XYZResource>?

**Comment by peavers** [comment]
@prawana-perera I'd also be very keen to see how you've done this...

**Comment by prawana-perera** [comment]
Hi,

This is the approach I took to implement JSON API serialisation and deserialisation using this library:

First my controller methods were setup to consume and produce JSON API, for example a POST (create resource) request:

```
@ResponseStatus(HttpStatus.CREATED)
public JSONAPIDocument<MyResource> createMyResource(@RequestBody @Validated JSONAPIDocument<MyResource> myResource) {

    // do stuff....
    MyResource model = doStuffToCreateModel(...)

    // e.g. decorate links, meta etc
    return createJSONApiDocumentFromModel(model);
}
```

And obvisouly `MyResouce` is a `jsonapi-converter` `@Type` e.g.:

```
@Type("MyResouce")
public class MyResouce {
    @Id
    private String id;

    // etc...
}
```

Then I created a `HttpMessageConverter` overriding the appropriate methods requried for serialisation and deserialisation:

My custom `HttpMessageConverter` extended the `AbstractJackson2HttpMessageConverter` (to make use of some methods).

In my constructor I initialised the `ResourceConverter` once as per:

```
// instance varaibles ...
private final ResourceConverter resourceConverter;

public MyCustomHttpMessageConverter(ObjectMapper objectMapper, List<String> basePackages) {
    super(objectMapper, MEDIA_TYPE);

    Assert.notNull(objectMapper, "An ObjectMapper must be provided.");
    Assert.notNull(basePackages, "Base packages to look for jsonapi-converter @Type annotations must be provided.");

    resourceConverter = new ResourceConverter(objectMapper);

    ClassPathScanningCandidateComponentProvider provider = new ClassPathScanningCandidateComponentProvider(false);
    provider.addIncludeFilter(new AnnotationTypeFilter(com.github.jasminb.jsonapi.annotations.Type.class));

    List<BeanDefinition> foundBeans = basePackages.stream()
      .map(pkg -> provider.findCandidateComponents(pkg))
      .flatMap(beanDefinitions -> beanDefinitions.stream())
      .collect(Collectors.toList());

    foundBeans.forEach(bean -> {
      try {
        Class modelClazz = Class.forName(bean.getBeanClassName());
        resourceConverter.registerType(modelClazz);
      } catch (ClassNotFoundException e) {
        throw new RuntimeException(e.getMessage(), e);
      }
    });

    // Used for POST (create) as we don't have ID yet!
    resourceConverter.disableDeserializationOption(DeserializationFeature.REQUIRE_RESOURCE_ID);
  }
```

As can be seen we use classpath scanning to auto detect all `@Type` resources and register them with the `ResourceConverter` resigistry. Also we had a customised `ObjectMapper` created else where and re-used by other converters so had to pass that in.

Then I over wrote the following methods:

```
@Override
  public boolean canRead(Type type, Class<?> contextClass, MediaType mediaType) {
    JavaType javaType = getJavaType(type, contextClass);
    return javaType.getRawClass().equals(JSONAPIDocument.class) && javaType.hasGenericTypes() && super.canRead(type, contextClass, mediaType);
  }

  @Override
  public boolean canWrite(Class<?> clazz, MediaType mediaType) {
    return clazz.equals(JSONAPIDocument.class) && super.canWrite(clazz, mediaType);
  }

  @Override
  protected void writeInternal(Object object, HttpOutputMessage outputMessage) throws IOException, HttpMessageNotWritableException {

    JSONAPIDocument jsonapiDocument = (JSONAPIDocument) object;

    try {
      if (jsonapiDocument.get() != null && Iterable.class.isAssignableFrom(jsonapiDocument.get().getClass())) {
        outputMessage.getBody().write(resourceConverter.writeDocumentCollection((JSONAPIDocument<? extends Iterable<?>>) jsonapiDocument));
      } else {
        outputMessage.getBody().write(resourceConverter.writeDocument(jsonapiDocument));
      }
    } catch (DocumentSerializationException e) {
      throw new HttpMessageNotWritableException(e.getMessage(), e);
    }
  }

  @Override
  public Object read(Type type, Class<?> contextClass, HttpInputMessage inputMessage) throws IOException, HttpMessageNotReadableException {
    JavaType javaType = getJavaType(type, contextClass);
    TypeBindings typeBindings = javaType.getBindings();

    // JSONAPIDocument has only 1 generic type e.g. JSONAPIDocument<User> or JSONAPIDocument<List<User>>
    JavaType containerType = typeBindings.getBoundType(0);
    Class<?> containerTypeClass = containerType.getRawClass();

    if (Iterable.class.isAssignableFrom(containerTypeClass)) {
      TypeBindings iterableTypeBindings = containerType.getBindings();
      JavaType itemType = iterableTypeBindings.getBoundType(0);
      return resourceConverter.readDocumentCollection(inputMessage.getBody(), itemType.getRawClass());
    } else {
      return resourceConverter.readDocument(inputMessage.getBody(), containerTypeClass);
    }
  }
```

Also then I created my `HttpMessageConverter` in configuration class:

```
@Configuration
public class MyCustomHttpMessageConverterConfig {

  @Bean(name = "myCustomHttpMessageConverter")
  public MyCustomHttpMessageConverter myCustomHttpMessageConverter() {
    return new MyCustomHttpMessageConverter(new ObjectMapper(), Arrays.asList("my.packages"));
  }
}
```

Any improvements or questions welcome. Also, perhaps this can be put into a small jar which can re-used for anyone wanting to use `jsonapi-converter` with Spring MVC/web.

**Comment by reecefenwick** [comment]
Thanks @prawana-perera, this looks good. Although I'm having the problem where it seems the [MappingJackson2HttpMessageConverter](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/converter/json/MappingJackson2HttpMessageConverter.html) bean is being invoked before my custom JSONAPI HttpMessageConverter, and since MappingJackson2HttpMessageConverter.canRead() is true it is creating an empty instance of JSONAPIDocument

Did you run into this?

**Comment by prawana-perera** [comment]
Hi @reecefenwick,

Yes we got it working. 

I forgot to mention, that we use media type `vnd.api+json`, so client sets the `Accept` header and we send back the `Content-Type` header with `vnd.api+json`. So for this media type our custom message converter gets invoked. The doco for the `MappingJackson2HttpMessageConverter` states 
```
By default, this converter supports {@code application/json} and {@code application/*+json}
 with {@code UTF-8} character set. This can be overridden by setting the
 {@link #setSupportedMediaTypes supportedMediaTypes} property.
```. 

E.g. 
```
public static final MediaType MEDIA_TYPE = new MediaType("application", "vnd.api+json", DEFAULT_CHARSET);
```
This is used in the constructor mentioned above.

According to the JSON-API v1 spec, `application/vnd.api+json` is the media type to use. Let me know how that goes.

**Comment by reecefenwick** [comment]
@prawana-perera thanks - turns out it was just a problem of my test not injecting the message converters, I assumed it was getting picked up automatically!

```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = Application.class, webEnvironment = RANDOM_PORT)
@ActiveProfiles("test")
public abstract class BaseIntegrationTest {

    public MockMvc createMockMvc(Object... controllers) {
        return MockMvcBuilders
            .standaloneSetup(controllers)
            .setMessageConverters(new JsonApiHttpMessageConverter()) // This was missing
            .build();
    }

}
```

**Comment by reecefenwick** [comment]
@prawana-perera Have you had problems where responses have a content type of "application/vnd.api+json?charset=UTF-8" (not allowed in JSONAPI spec), even when I create my MediaType without the charset param`new MediaType("application", "vnd.api+json")` 

Also I had to update the signature for `writeInternal()` to override the correct method for serialization to the client.

```java
protected void writeInternal(Object object, Type type, HttpOutputMessage outputMessage)
```

**Comment by prawana-perera** [comment]
Hi @reecefenwick 

No I have not seen `"application/vnd.api+json?charset=UTF-8" (not allowed in JSONAPI spec)`, can you please elaborate?

**Comment by dementiacs** [comment]
@prawana-perera are you able to post a full code example of your JSONApi HttpMessageConverter for consuming JSONApi data?
