### ISSUE TITLE
Expected date for next release

### ISSUE THREAD

**Issue by jordanmueller** [jasminb/jsonapi-converter#139]
Hello, 

Is there an expected date for an 0.8 release?  There are some fixes in develop that we'd like to use.

Thank you,

Jordan

**Comment by jasminb** [comment]
Hey @jordanmueller,

I will release the next version during the weekend.

**Comment by jordanmueller** [comment]
Thank you!

**Comment by jasminb** [comment]
Hey @jordanmueller, 0.8 is released. Closing the issue.

**Comment by jordanmueller** [comment]
Thank you.
