### ISSUE TITLE
NullPointerException after converting

### ISSUE THREAD

**Issue by SPoket** [jasminb/jsonapi-converter#140]
**From the server I get this JSONObject:**
`{"data":[{"type":"player","id":"e119f90c-2ee4-11e5-b333-06eb725f8a76","attributes":{"createdAt":"2017-08-24T19:03:55Z","name":"SPoket","shardId":"eu","stats":{"elo_earned_season_4":1463.6810290764283,"elo_earned_season_5":1637.6657601131212,"elo_earned_season_6":1625.7512200558283,"elo_earned_season_7":1526.3999086023439,"karmaLevel":2,"level":30,"lifetimeGold":15266.375,"lossStreak":0,"played":2874,"played_ranked":1129,"skillTier":18,"winStreak":0,"wins":1108,"xp":175450},"titleId":"semc-vainglory"},"relationships":{"assets":{"data":[]}}}],"links":{"self":"https://api.dc01.gamelockerapp.com/shards/eu/players?filter[playerNames]=SPoket"},"meta":{}}`

**And this is my model class:**

@Type("player")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Player {

    @Id
    private String id;

    private String name;

    @JsonProperty("stats")
    private PlayerStats playerStats;

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public PlayerStats getPlayerStats() {
        return playerStats;
    }

    public List<Asset> getAssets() {
        return assets;
    }

    @Relationship("assets")
    private List<Asset> assets;

    @Override
    public String toString() {
        return "Player{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", playerStats=" + playerStats +
                '}';
    }

}`

**And PlayerStats:**
`@JsonIgnoreProperties(ignoreUnknown = true)
public class PlayerStats {

    private int wins;
    private int winStreak;
    private int lossStreak;

    private int karmaLevel;
    private int skillTier;

    private int xp;
    private int level;
    private double lifetimeGold;

    private int played;

    public int getWins() {
        return wins;
    }

    public int getWinStreak() {
        return winStreak;
    }

    public int getLossStreak() {
        return lossStreak;
    }

    public int getXp() {
        return xp;
    }

    public int getLevel() {
        return level;
    }

    public double getLifetimeGold() {
        return lifetimeGold;
    }

    public int getPlayed() {
        return played;
    }

    public int getPlayedRanked() {
        return playedRanked;
    }

    @JsonProperty("played_ranked")
    private int playedRanked;

    @JsonProperty("elo_earned_season_4")
    private int eloSeason4;

    @JsonProperty("elo_earned_season_5")
    private int eloSeason5;

    @JsonProperty("elo_earned_season_6")
    private int eloSeason6;

    @JsonProperty("elo_earned_season_7")
    private int eloSeason7;

    @Override
    public String toString() {
        return "PlayerStats{" +
                "playedRanked=" + playedRanked +
                ", played=" + played +
                ", lifetimeGold=" + lifetimeGold +
                ", level=" + level +
                ", xp=" + xp +
                ", lossStreak=" + lossStreak +
                ", winStreak=" + winStreak +
                ", wins=" + wins +
                '}';
    }

    public int getKarmaLevel() {
        return karmaLevel;
    }

    public int getSkillTier() {
        return skillTier;
    }

    public int getEloSeason4() {
        return eloSeason4;
    }

    public int getEloSeason5() {
        return eloSeason5;
    }

    public int getEloSeason6() {
        return eloSeason6;
    }

    public int getEloSeason7() {
        return eloSeason7;
    }
}`

**Convert to Player:**

`
@Override
public void onSuccess(int statusCode, Header[] headers, JSONObject response) {
String str = response.toString();
InputStream is = new ByteArrayInputStream(str.getBytes());
Player player = resourseConverter.readDocument(is, Player.class).get();
}`
**But Player class after converting is an null. What I'm doing wrong?**

**Comment by jasminb** [comment]
Hey @SPoket,

Your API is returning collection of elements rather than single one, use:

```java
resourceConverter.readDocumentCollection(is, Player.class);
```

**Comment by SPoket** [comment]
Thanks @jasminb, it helped me.
