### ISSUE TITLE
CustomIdHandler for a resource

### ISSUE THREAD

**Issue by razzpoker50** [jasminb/jsonapi-converter#142]
I was trying to implement a CustomIdHandler for my use case, where in the `id` is a combination of 2 properties. courseName and courseId. 

**CourseIdhandler.java**

```
public class CourseIdHandler implements ResourceIdHandler {

    public CourseIdHandler() {
       
    }

    @Override
    public String asString(Object identifier) {
        if (identifier != null) {
            return String.valueOf(identifier);
        }
        return null;
    }

    @Override
    public String fromString(String source) {
        return source;
    }
}
```

**Course.java**

```
@Type("course")
public class Course {
   @Id(CourseIdHandler.class)
    private String id;
    private long courseName;
    private long courseId;
    
   public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public long getCourseId() {
        return courseId;
    }

    public void setCourseId(long courseId) {
        this.courseId = courseId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        String myId =  this.courseName + "_" + this.courseId;
        this.id = myId;
    }
}
```
I am trying to set the `id` in the setter and was expecting the id to be set when `CourseIdHandler` is resolved. But it is always null. I am pretty sure I got it wrong, and I am trying to find the correct approach for the above scenario.

**Comment by jasminb** [comment]
Hello @razzpoker50,

Lib is not using set/get methods and relies on direct field access. However your `id` field should not be `null` if it was returned from the service.

Can you provide the input you are using that produces `null id`?

**Comment by razzpoker50** [comment]
Hello @jasminb 
Id is not a field that is returned from the service. Even though this is a contrived example, service returns only courseId and courseName and I am trying to build a custom id by having an additional property on the model.

**Comment by jasminb** [comment]
Why not simply add a get method that will do what-ever on your model instance?

**Comment by razzpoker50** [comment]
Thanks for the quick reply @jasminb. I think I just modified the setter and not the getter method. Let me check if that works for my use case. I thought customer Id handles  have to be implemented since the ID in this scenario is not an atomic entity. Also the clarification around when to use is makes sense.

**Comment by razzpoker50** [comment]
@jasminb That did the trick. Thank you for the help :)
