### ISSUE TITLE
Includes without relationships

### ISSUE THREAD

**Issue by jsteinbrunner** [jasminb/jsonapi-converter#143]
I'm relatively new to JSON API, and really appreciate the work you have done on this library! 

We are looking to support side effects in our API and wanted to add these to the `included` section of the payload.  From what we can see, it looks like we can only add objects to `included` by defining a relationship in our model.

In some cases, there are side effects that aren't a relationship to the resource in the payload and we just want to add it to the `included` section without defining a relationship.  Is this something you have encountered before?  Is this the correct way to implement side effects in JSON API?

Here is an example payload to illustrate what we want to do. This is a contrived example, but it is simply marking a blog post as featured and the side effect is a different (unrelated) blog post was changed to be unfeatured.

```
{
   "data":{
      "type":"post",
      "id":"id10",
      "attributes":{
         "title":"My latest blog post",
         "featured":true
      }
   },
   "included":[
      {
         "type":"post",
         "id":"id1",
         "attributes":{
            "title":"My first blog post",
            "featured":false
         }
      }
   ]
}
```

**Comment by jasminb** [comment]
Hello @jsteinbrunner,

Included section is intended to be used for avoiding following resource relationship. One can choose to provide those and avoid network round-trip.

What you could use instead is `meta`, see https://github.com/jasminb/jsonapi-converter#top-level-links-and-meta. This allows you to return arbitrary meta-data in the response and be able to access it.

If you define a class called `BlogCreateSideEffects` and return it as `meta`, you can do the following:

```java

JSONAPIDocument<Blog> blogCreateResult = ...
BlogCreateSideEffects sideEffects = blogCreateResult.getMeta(BlogCreateResult.class);
```

**Comment by jsteinbrunner** [comment]
@jasminb 
Thanks so much for the timely reply!

The JSON API spec doesn't seem to define much around side affects, so wasn't sure what the appropriate solution was. I think we can work with the `meta` solution you proposed.

Thanks for your feedback!
