### ISSUE TITLE
deserialization of type when two classes marked with same type

### ISSUE THREAD

**Issue by uddyami** [jasminb/jsonapi-converter#147]
I have classes as follows:
```
@Type("card")
public class A {
}


@Type("card")
public class B {
}
```

I use class B exclusively only during POST BODY calls ..  How do ensure my response is always read as `class A`

**Comment by jasminb** [comment]
Hello @uddyami,

One simple  solution for your problem is to have two different instances of the `ResourceConverter`, use one for serialising requests sent to the server and another one for reading responses.

**Comment by uddyami** [comment]
sounds good! thanks
