### ISSUE TITLE
JsonInclude.Include.NON_NULL

### ISSUE THREAD

**Issue by kresovic-milos** [jasminb/jsonapi-converter#151]
Hi,

I am unsuccessfully trying to force serialization of `null` values.

I discovered that it's fixed in the `ResourceConverter` class on the line 108:
```
objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
```

Is it possible to change this behavior or I should do it with on my own `ResourceConverter`?

Thanks,
Milos

**Comment by jasminb** [comment]
Hello @kresovic-milos,

I will move the line in question so it is invoked only if external mapper is not provided. This will allow users to control mapping options and will not override user defined settings.

**Comment by kresovic-milos** [comment]
great!
thank you.
