### ISSUE TITLE
Type annotation doesn't allow name

### ISSUE THREAD

**Issue by tschaka1904** [jasminb/jsonapi-converter#16]
Hi, 

I don't know why, but I can't give `@Type` a name like `@Type(name = "MyClass")`. It only allows me `@Type("MyClass")`, but it seems like that it doesn't work. :( 

Thanks,
Max

**Comment by jasminb** [comment]
Hello,

`Type` annotation has only one parameter which is to specify the type name.

Name can be specified in following manner:

```
@Type("my-type-name")
@Type(value = "my-type-name")
```

**Comment by tschaka1904** [comment]
Cheers!
