### ISSUE TITLE
How to set top level meta data?

### ISSUE THREAD

**Issue by marceloverdijk** [jasminb/jsonapi-converter#164]
I noticed the top level meta data is defined as:

```
	/**
	 * A map of meta fields, keyed by the meta field name
	 */
	private Map<String, ?> meta;

	/**
	 * Get meta data.
	 *
	 * @return {@link Map} meta
	 */
	public Map<String, ?> getMeta() {
		return meta;
	}
```

Is there a reason why the value is `?` and not e.g. `Object`?

How should I add a key/value to the map?
Note the meta map can be null as well.

What I'm doing now is:

```
JSONAPIDocument<List<D>> document = new JSONAPIDocument<>(resources);
Map<String, Object> meta = new HashMap<>();
meta.put(PAGE_INFO, new PageInfo(page));
document.setMeta(meta);
```

but I think this could be simplified to something like:

```
JSONAPIDocument<List<D>> document = new JSONAPIDocument<>(resources);
document.getMeta().put(PAGE_INFO, new PageInfo(page));
```

but this won't work as `getMeta()` will return a `null` map and also it does not accept `PageInfo` as value.

Any ideas?

**Comment by jasminb** [comment]
Intention here was to guard state but as I looked at it now, there is way to modify state by `getMeta()` and than performing mutations on returned `Map`. 

I don't have anything against introducing a change where `getMeta()` will lazily initialise internal state and return it in case its `null`.

**Comment by marceloverdijk** [comment]
Do you agree making it `private Map<String, Object> meta;` then?
Instead of the wildcard `Map<String, ?>` as it's not so useful.

If so I can make a PR lazily initialising the meta and adding convenient method like `addMeta(String, Object)`.

Let me know.

**Comment by jasminb** [comment]
Sounds good.

**Comment by marceloverdijk** [comment]
OK will do!

**Comment by sobakasu** [comment]
is there any way to set meta at the top level when using retrofit?

**Comment by marceloverdijk** [comment]
Closing this as per commit #167
