### ISSUE TITLE
[0.8.1] Retrofit requestBodyConverter uses wrong ResourcesConverter

### ISSUE THREAD

**Issue by MarcoCapoferri** [jasminb/jsonapi-converter#171]
Hi guys i'm using jsonapi-converter 0.8.1 and i'm providing a different ResourceConverter for serialization and deserialization.

I found an issue in JSONAPIConverterFactory at line 89 ( https://github.com/jasminb/jsonapi-converter/blob/develop/src/main/java/com/github/jasminb/jsonapi/retrofit/JSONAPIConverterFactory.java )

This is the current wrong line:
`if (retrofitType.isValid() && deserializer.isRegisteredType(retrofitType.getType())) {`

But it should be

`if (retrofitType.isValid() && deserializer.isRegisteredType(retrofitType.getType())) {`

As you can see in the actual code deserilizer ResourceConverter is used for serialization.

**Comment by jasminb** [comment]
Please feel free to open up a pull request and fix the issue.
