### ISSUE TITLE
JSONAPIConverterFactory uses types from deserializer to serialize object

### ISSUE THREAD

**Issue by budius** [jasminb/jsonapi-converter#174]
During data serialization (aka `requestBodyConverter`) the JSONAPIConverterFactory is using `deserializer.isRegisteredType` and the uses the `serializer` for the `JSONAPIRequestBodyConverter`.

This breaks the ability to properly handle outgoing and incoming data differently.

**Comment by budius** [comment]
So I was already cloning (https://github.com/sensorberg-dev/jsonapi-converter) was gonna fix and open a PR when I noticed it was fixed on the last commit https://github.com/jasminb/jsonapi-converter/issues/171 - https://github.com/jasminb/jsonapi-converter/commit/a68ff12b62744963485323cdcda294a062dba990

any ETA?

**Comment by jasminb** [comment]
Hey @budius, there are few more things that I'm considering before creating a minor release (should take a week). In meanwhile you can use 'SNAPSHOT' version.

**Comment by iadcialim** [comment]
@budius @jasminb Im using this library to convert the Json response that uses JSONAPI spec. But can you teach how to have a separate converter for the requestBody? Thanks
