### ISSUE TITLE
How to annotated a one to many relationship?

### ISSUE THREAD

**Issue by tschaka1904** [jasminb/jsonapi-converter#18]
Hi, 

how do I have to annotate a one to many relationship?

Thanks,
Max

**Comment by jasminb** [comment]
Hello,

If object `A` has many `B` objects, you would add a field to `A` object that would be `java.util.List<B> objects`.

Added attribute needs to be annotated with `@Relationship(name = "relationship_name")` annotation.

Please see README file for more detailed example.

Kind regards,
Jasmin

**Comment by dodos90** [comment]
Hello,

First of all, sorry to comment again on a closed issue, but I think I found a (little) bug :)
I tried to serialize an `User` object which has a relationship to multiple `UserBoxMap` items.

In my `User` class, if the `UserBoxMap` attribute is defined as follows : 

`private Set<UserBoxMap> userBoxMap = new HashSet<>();`

The serialization fails with an exception : 
`java.lang.NullPointerException
at com.github.jasminb.jsonapi.ResourceConverter.getDataNode(ResourceConverter.java:684)
at com.github.jasminb.jsonapi.ResourceConverter.writeDocument(ResourceConverter.java:566)`

But if my attribute is defined as follows : 

`private List<UserBoxMap> userBoxMap = new ArrayList<>();`

The serialization works great.
Is it a normal behavior to deal with Lists and Sets differently ? I think I can change every serializable Set to a List in my project (I don't think it will have a too big impact), but I just wanted to let you know !

Thanks a lot.

**Comment by jasminb** [comment]
Hey @dodos90, thanks for taking the time and documenting your findings. You are correct about the `List`, library does not support any other collection type. Honestly, only reason I can come up with for doing so is simplicity in order to avoid making decision what type of collection to create when deserialising relationship.
