### ISSUE TITLE
Can't add JSONAPIConverterFactory to retrofit

### ISSUE THREAD

**Issue by faeronsayn** [jasminb/jsonapi-converter#19]
I'm using the following code

```
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(getResources().getString(R.string.base_url))
                .addConverterFactory(new JSONAPIConverterFactory(new ObjectMapper(), User.class, Friendship.class))
                .client(client)
                .build();
```

Essentially the way it's done in the readme.

However there is a type mismatch error 

```
Error:(89, 38) error: incompatible types: JSONAPIConverterFactory cannot be converted to Factory
```

I'm using retrofit 2.0.1 and jsonapi-converter 0.2. I wonder if the apis have changed since the example in the readme or am I just missing something here? 

Any ideas?

**Comment by faeronsayn** [comment]
Seems like this is not updated for retrofit2? Because it's importing `retrofit.Converter` instead of `retrofit2.Converter` here.

https://github.com/jasminb/jsonapi-converter/blob/develop/src/main/java/com/github/jasminb/jsonapi/retrofit/JSONAPIConverterFactory.java#L7

Should I make a pr with a fix?

**Comment by jasminb** [comment]
Hey,

Sorry for the late reply. I will update the dependency to he 2.x.x retrofit and do the necessary code changes required.

Regards

**Comment by jasminb** [comment]
Fixed.
