### ISSUE TITLE
Difficulty Serialising a List of objects

### ISSUE THREAD

**Issue by dementiacs** [jasminb/jsonapi-converter#191]
Consider this snippet.

```
List<Fault> listOfFaults = ....
JSONAPIDocument<List<Fault>> document = new JSONAPIDocument<>(listOfFaults);
```
How do I then serialise that into a String?

when I try

`bytes = converter.writeDocument(document);`

I get an exception

com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode

What am I doing wrong?

Fault itself is a simple class with id, type and a few attributes and serialises fine when it is a single object.

**Comment by uddyami** [comment]
I think it should be `converter.writeDocumentCollection(document)`

**Comment by peavers** [comment]
Here is a helper method I use, just pass in the list. 

```
    @Override
    public String writeList(Iterable<?> iterable) {
        JSONAPIDocument<Collection<?>> listJSONAPIDocument = new JSONAPIDocument<>(
                (Collection<?>) iterable);

        byte[] bytes = new byte[0];
        try {
            bytes = converter.writeDocumentCollection(listJSONAPIDocument);
        } catch (DocumentSerializationException e) {
            e.printStackTrace();
        }

        return new String(bytes);
    }
```

**Comment by jasminb** [comment]
Closing as advice for proper lib usage was provided in comments.
