### ISSUE TITLE
Add ProGuard rule on README for ResourceIdHandler

### ISSUE THREAD

**Issue by budius** [jasminb/jsonapi-converter#194]
After much debugging and having issues, I've got the point to add the following rule my Proguard:

```
-keep class * implements com.github.jasminb.jsonapi.ResourceIdHandler
```

This could be used just on the built-in `StringIdHandler` for my project, but this rule seems to better cover the cases. Without it the application would keep crashing on [this line of the ConverterConfiguration](https://github.com/jasminb/jsonapi-converter/blob/develop/src/main/java/com/github/jasminb/jsonapi/ConverterConfiguration.java#L121) with `InstantiationException` on the `StringIdHandler`.

Maybe someone that better understand ProGuard can improve on keeping just some specific part of the class instead of the whole thing.

But submitting the info here for whoever stumbles on it.

**Comment by jasminb** [comment]
Note added to README.md, closing the issue.
