### ISSUE TITLE
Is there a way to ignore filed when parsing?

### ISSUE THREAD

**Issue by youngliangzhang** [jasminb/jsonapi-converter#199]
I added one map field to the class for using in local. But I got json parsing error even though there is no this name field in api response.
This is error message: "Can not find a (Map) Key deserializer for type [simple type, class ***]."
So I need to ignore this field when parsing.

**Comment by iadcialim** [comment]
@youngliangzhang Have u found way to this?

**Comment by RoqueManuel** [comment]
Hi, I'm using this library and during development our team changes some times the response to include new files, here I think you can use [fields] in your request to get only the fields that really want from the endpoint, other way is to mark your class as `@JsonIgnoreProperties(ignoreUnknown = true)` that will ignore all not defined properties.
