### ISSUE TITLE
NullPointerException while parsing jsonapi object

### ISSUE THREAD

**Issue by fabricehong** [jasminb/jsonapi-converter#2]
hi

my json object look like :
```
{
	"data" : {
		"id" : "1"
		...
	}
	...
}
```

I have a NullPointerException in ResourceConverter class. in method "setIdValue", idValue is null at line : "idField.set(target, idValue.asText());"

Debuging the method readObjectCollection in ResourceConverter, I saw that while looping over the properties of the data element,
the readObject method used here expect the source ton contain a json container with an 'id' key.

the type of the returned object from e.get("data") is "ObjectNode"

With this object type, the returned element from objectNode.iterator() from jackson-databind-2.7.1, is the list of values (ex: "1"), not the expected list of object (ex : "id"=>"1").

code of readObjectCollection method:
```
public <T> List<T> readObjectCollection(byte[] data, Class<T> clazz) {
        try {
            JsonNode e = this.objectMapper.readTree(data);
            Map included = this.parseIncluded(e);
            ArrayList result = new ArrayList();
            Iterator i$ = e.get("data").iterator();
            while(i$.hasNext()) {
                JsonNode element = (JsonNode)i$.next();
                Object pojo = this.readObject(element, clazz, included);
                result.add(pojo);
            }
            return result;
        } catch (Exception var9) {
            throw new RuntimeException(var9);
        }
    }
```

**Comment by jasminb** [comment]
Hello,

Reason for the `NPE` is a fact that you are using `readObjectCollection` instead of `readObject`;

`readObjectCollection()` is expecting a collection of elements to be present:

```
{
  "data" : [
    {
      "id" : "id",
      "type" : "some-type"
    }
  ]
}
```

If you switch to `readObject` method, it should work fine.

**Comment by fabricehong** [comment]
Hi,

I'm not using readObjectCollection by myself, JSONAPIResponseBodyConverter is doing it.

I'm initializing retrofit this way : 

```
 ObjectMapper objectMapper = new ObjectMapper();

        return new Retrofit.Builder()
                .addConverterFactory(new JSONAPIConverterFactory(objectMapper, Offer.class, OfferVariation.class, Product.class))
                .baseUrl("https://api-qmob.qoqa.com/v1/")
                .client(client)
                .build();
```

as suggested in the README.md

my Offer object, is something like that:

```
@Type("offer")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Offer {
    @Id
    private String id;

```

should I init retrofit differently ?

**Comment by jasminb** [comment]
Hey,

Do you mind sharing your retrofit service interface?

It looks like you defined a method in your service stub that expects `List<YourType>` as result and it should be `YourType` instead.

**Comment by fabricehong** [comment]
my bad sorry. My interface didn't match the json :

```
@GET("offers/current")
@Headers("Content-Type:application/json")
Call<List<Offer>> getCurrentDeal(@Query("locale") String locale, @Query("website_identifier") String websiteId);
```

while it should be

```
Call<Offer> getCurrentDeal(@Query("locale") String locale, @Query("website_identifier") String websiteId);
```

I suggest to check for type of the jsonelement, and throw an addequate exception if it's expecting a list while it's not

thanks a lot for your very fast support

**Comment by jasminb** [comment]
No problem at all, I've already pushed change to develop that validates inputs and throws exceptions in case data being parsed is not matching expected inputs.

**Comment by dodos90** [comment]
Hi,

I've got a similar issue with the following JSON :
`{  
   "data":[  
      {  
         "type":"device",
         "id":4001,
         "attributes":{  
            "id":4001,
            "serial":"0a621724c372cc07",
            "activationCode":"4000123412341235",
            "creationDate":1467099796000,
            "lastCommDate":0
         },
         "relationships":{  
            "userDeviceMap":{  
               "data":[  
                  {  
                     "type":"user_device_map",
                     "id":4001
                  }
               ]
            }
         }
      }
   ],
   "included":[  
      {  
         "type":"user_device_map",
         "id":4001,
         "attributes":{  
            "id":4001,
            "active":true,
            "name":"Device1",
            "ack":true,
            "creationDate":1467099796000
         }
      }
   ]
}`

When I try to deserialize this JSON, I got the following error : 

`java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.Field.set(java.lang.Object, java.lang.Object)' on a null object reference
at com.github.jasminb.jsonapi.ResourceConverter.setIdValue(ResourceConverter.java:523)
at com.github.jasminb.jsonapi.ResourceConverter.readObject(ResourceConverter.java:297)
at com.github.jasminb.jsonapi.ResourceConverter.parseRelationship(ResourceConverter.java:483)`


This JSON is obtained through a Retrofit client created like this : 

`this.retrofit = new Retrofit.Builder().baseUrl("xxx)
                .addConverterFactory(new JSONAPIConverterFactory(new ResourceConverter(Device.class)))
                .client(new OkHttpClient.Builder().build())
                .build();`

My Device class looks like this : 

`@Type("device")`
`@Parcel`
`public class Device extends DeviceBeforeCreation implements Model
{`
    `@Id String id;`
    `// SOME ATTRIBUTES HERE`
    `@Relationship("userDeviceMap")`
    `private UserDeviceMap userDeviceMap;`

   ` // GETTERS AND SETTERS`
`}`

And my "UserDeviceMap" looks like this : 

`@Type("user_device_map")`
`@Parcel`
`@JsonIgnoreProperties(ignoreUnknown` = true)
`public class UserDeviceMap
{`
    `@Id private String id;`
    `    public UserDeviceMap()
    {
    }
`

    // GETTERS AND SETTERS
`}`

I don't know if there is something missing from the JSON, or if my client configuration is wrong... I just need to read the data from the "included" block inside my UserDeviceMap object...

Thanks for your help !

**Comment by jasminb** [comment]
Hey @dodos90, `UserDeviceMap` also needs to be annotated with `Type` and registered in `ResourceConverter` when creating it (besides `Device` class).

**Comment by dodos90** [comment]
Oh yeah ! I didn't really understand that we need to add the compound classes (like `UserDeviceMap`) to the `ResourceConverter` as well. Now it works perfectly, thanks !
