### ISSUE TITLE
Setting meta to JsonApiDocument

### ISSUE THREAD

**Issue by bradroid** [jasminb/jsonapi-converter#202]
When my app is running meta serialization & mapping works fine. In tests however, `jsonApiDocument.getMeta` always returns null. I simplified the tests to isolate the problem, can you please check it out?
The last assertion fails, myMeta val is null.

```
@RunWith(MockitoJUnitRunner::class)
class MetaTests {

    @Test
    fun test1() {
        val jsonApiDocument = JSONAPIDocument(null)

        val meta = HashMap<String, Any>()
        meta["count"] = 5

        assertEquals(null, jsonApiDocument.meta)
        jsonApiDocument.meta = meta
        assertEquals(meta, jsonApiDocument.meta)

        val myMeta = jsonApiDocument.getMeta<MyMeta>(MyMeta::class.java)
        assertEquals(MyMeta(5), myMeta)
    }
}

data class MyMeta(
        @JsonProperty("count") val count : Int)
```

**Comment by jasminb** [comment]
Here is the imlementation of the method you are using: 

```java
	public <T> T getMeta(Class<?> metaType) {
		if (meta != null && deserializer != null) {
			return (T) deserializer.convertValue(meta, metaType);
		}

		return null;
	}
```

Doc object has its deserialiser instance == null, use a proper constructor and it should work.

**Comment by bradroid** [comment]
Thanks very much, I see that I need to construct JSONAPIDocument by passing deserializer (ObjectMapper) in as a second argument.
