### ISSUE TITLE
readDocument vs readDocumentCollection

### ISSUE THREAD

**Issue by feludens** [jasminb/jsonapi-converter#207]
Hi Jasmin,

This is more a question than an issue, but I hope you can help.

I am calling an API that might return either a collection or a single object in the data node. Does the library have a way to detect wether to use **readDocument** or **readDocumentCollection**? 

If not, how are you handling such scenarios?

Thanks!

**Comment by peavers** [comment]
The standard way would be to read it always as a collection, then if there is only a single object it would just be a collection of one, which your logic could handle. Assumed you iterated over the result, regardless if it's one 1 or n you'd be fine.

**Comment by feludens** [comment]
I completely agree with you. The service should return a collection regardless of the number of results.
However, the JSON API docs specify that 

> The document’s “primary data” is a representation of the resource **or** collection of resources targeted by a request.

Meaning that it can be a single object as well. Unfortunately, that's the case of the api I have to work with right now. Hence why I am asking if the library has any capabilities to handle the case where the client doesn't know wether to expect a single object or a collection.

**Comment by feludens** [comment]
**UPDATE:** the backend developer agreed that those specific endpoints should always return a collection, so I am good, but in case someone else might be running into this issue, I'd still appriciate if you could answer the question above! Thanks.

**Comment by jasminb** [comment]
@feludens 

From the perspective of the lib, it already respects (and supports) that APIs return either single `{}` or `[]`, however you, as a developer, must now how the API behaves and use proper methods.

It would be relatively simple to provide a new API that handles this use-case (collection or single doc), however I think it would be wrong thing to do. It would promote bad API design and it would, overall, produce lower quality code.

Imagine things like:

```java

JSONAPIDocument<MyType> result = client.get(....);

MyType object;
if (result.isCollection()) {
    object = result.getCollection().iterator().next();
} else {
   object = result.get();
}
```

**Comment by feludens** [comment]
Yeah, I completely agree with you. This shouldn't be something the client needs to handle to begin with. Thanks for the answers though!
