### ISSUE TITLE
Link resolution

### ISSUE THREAD

**Issue by emetsger** [jasminb/jsonapi-converter#21]
This is a question more than an issue-

`ResourceConverter.handleRelationships(...)` only considers the `self` link when attempting resolution.  However, I am working with some JSON relationships that look like:

    "relationships": {
                "files": {
                    "links": {
                        "related": {
                            "href": "http://osf:8000/v2/nodes/mrusa/files/",
                            "meta": {}
                        }
                    }
                }

When `handleRelationships(...)` encounters this JSON, it will not attempt resolution, because there is no links member named `self`, only a member named `related` (note that this JSON complies with the [spec](http://jsonapi.org/format/#document-resource-object-relationships), which requires one of a `links`, `data`, or `meta` object).

Per the JSON-API 1.0 [spec](http://jsonapi.org/format/#document-resource-object-relationships) it seems that the `links` object for a Relationship can contain both `self` and `related` links, where

- a `GET` on a `self` link returns the relationship link object
- a `GET` on a `related` link returns the _resource objects_

So, what should the behavior of `ResourceConverter.handleRelationships(...)` be when it encounters a Relationship object with a `links` member that has no `self` but has a `related` member?

**Comment by emetsger** [comment]
I should say that if we arrive on the proper behavior, I'm happy to submit a PR!

**Comment by emetsger** [comment]
For my part, you can see a gist of my model class and resolver implementation [here](https://gist.github.com/emetsger/b89d3142174c65306e99cd6006fd9a09), which I suspect is a typical vanilla implementation.  The gist also contains the example relationship object I'm trying to parse.

**Comment by jasminb** [comment]
Hey,

We could approach this with adding additional property into relationship annotation that would instruct the parser what link to consume when resolving relationship.

In case instruction is not specified, parser could be changed in a way to attempt one and than another if present (self/related).

Regards,
Jasmin

**Comment by emetsger** [comment]
Yes, that is what I was thinking. In fact, the 'resolve' attribute could be
changed from a boolean to the type of the link (self/related). I'm not sure
how palatable that would be, though, if you are concerned about backwards
compatibility.

**Comment by jasminb** [comment]
I would keep `resolve` in order not to break backwards compatibility. New property named `resolutionType` should be introduced that lets one choose between `ResolutionType.SELF` and `ResolutionType.RELATED` options.

Converter can be changed so if `resolutionType` is present, `resolve` flag is ignored (so its usage is not forced).

Only problem remaining would be what if `resolve` is present but type is not specified, do we try both options and see which one works or only one, and if one, which?

PS
I'm not sure about naming used above :)

**Comment by emetsger** [comment]
I would propose to call the new attribute `relType` (for relationship type) instead of `resolutionType`, what do you think?
* `relType = RelType.RELATED`
* `relType = RelType.SELF`

The type of the `relType` attribute should be a `String`, I think, to allow any kind of relationship type.  But of course have constants for `RELATED` and `SELF`.

If `relType` attribute is present on the `@Relationship` annotation:
* and the `resolve` attribute is missing, then `resolve` implicitly equals `true`

If `resolve` attribute is present on the `@Relationship` annotation and equals `true`:
* and the `relType` attribute is missing, then I think an exception should be thrown; i.e. `relType` is required when `resolve == true`.  This is a modeling issue (that is, the selection of which relType to follow), so I think it must be explicit by the user of the JSON API converter.

If `resolve` attribute is present on the `@Relationship` annotation and equals `false`:
* then the presence or absence of `relType` is ignored, because no resolution is performed.

Thoughts?

**Comment by jasminb** [comment]
Im thinking about deprecating 'resolve' and than removing it after in the release after next.

As for using `String` for the relType, I don't like it, constant wont help since it wont be obvious to the users.

Agree on the handling combo of resolve = true and missing relType.

**Comment by emetsger** [comment]
> Im thinking about deprecating 'resolve' and than removing it after in the release after next.

+1

> As for using `String` for the relType, I don't like it, constant wont help since it wont be obvious to the users.

Ok, I was just considering the use case of modeling a custom relationship type that isn't "self" or "related".  I'm not sure if that's a valid use case or not.

> Agree on the handling combo of resolve = true and missing relType.

+1

**Comment by jasminb** [comment]
Hey,

Just wondering if you were gonna tackle this one or should I implement it?

Regards

**Comment by emetsger** [comment]
I should have a PR to submit in the next couple of hours!  Working on the
test!  Thanks :)

**Comment by emetsger** [comment]
This is what I have so far:
https://github.com/emetsger/jsonapi-converter/tree/reltype-resolution

Essentially `testLinksAsObjects` and `testResolveRelType` are the same test.  So they could be merged into a single unit test if you're ok with that.  

It's tricky to test these different conditions against a single instance of a model, so I was thinking a longer-term solution may be to use something like [Modello](https://codehaus-plexus.github.io/modello/modello.html) to generate models for simulating various test conditions.

**Comment by jasminb** [comment]
Hey,

Please rebase to latest dev, to avoid conflicts later on.

As for `relType`, taught we agreed on using an `Enum`?

Will check out modello :)

Regards

**Comment by emetsger** [comment]
@jasminb yes, I'll make it enum, and rebase!  I just updated my comment with things I think that still need doing.  I can take a stab at a branch that uses modello to generate your existing model, too.

**Comment by jasminb** [comment]
Sure, if using Modello makes it more simple/easier to maintain, im all for it.

**Comment by emetsger** [comment]
Ok, faeb60 rebased on develop, and updates to using a RelType enum, let me know if I went overboard making it a stand-alone enum with the `getRelName()` method.

I can collapse the `testResolveRelType()` and `testLinksAsObjects()` tests if you like, and submit an official PR...

**Comment by jasminb** [comment]
Sure thing, you can collapse and submit PR.
