### ISSUE TITLE
@Meta does not work

### ISSUE THREAD

**Issue by iadcialim** [jasminb/jsonapi-converter#210]
I have these models

```
open class BaseModel {
    @Id
    var id: String = ""
    var type: String? = null
}

@Type("user")
class UserModel : BaseModel() {

    @JsonProperty
    var email: String? = null

    @Meta
    var meta: MetaModel? = null

    class MetaModel {
        @JsonProperty("auth_token")
        var authToken: String? = null
        var message: String? = null
    }
}
```

json 

```
{
  "data": {
    "id": "277",
    "type": "user",
    "attributes": {
      "email": "iad@xyz.com",
    }
  },
  "meta": {
    "auth_token": "xxxxxxxx",
    "message": "Login successful"
  }
}
```

meta is always null. Anything I miss?

**Comment by iadcialim** [comment]
@jasminb Is it a bug?

**Comment by jasminb** [comment]
@iadcialim you are dealing with global meta object so it should not be part of your type class.

Global meta can be accessed from `JSONAPIDocument' using `getMeta` which allows for typed results.

See https://github.com/jasminb/jsonapi-converter/blob/develop/src/test/java/com/github/jasminb/jsonapi/ResourceConverterTest.java#testReadWithMetaAndLinksSection for more details.

**Comment by iadcialim** [comment]
Ok thanks
