### ISSUE TITLE
Server-side generation of id

### ISSUE THREAD

**Issue by bensullivan** [jasminb/jsonapi-converter#217]
Hi

First up - thanks so much for this library!

I was looking at the JSON:API spec and noticed that is wasn't mandatory to submit an id when creating a resource.

Is there any way to deserialise a request with this library without an id attribute is . POST so that the id UUID could then be generated on the server side?

Thanks!!

Ben

**Comment by jasminb** [comment]
Hello @bensullivan,

You can achieve it by using `DeserializationFeature.REQUIRE_RESOURCE_ID` flag:

```java
converterInstance..disableDeserializationOption(DeserializationFeature.REQUIRE_RESOURCE_ID);
```

**Comment by bensullivan** [comment]
Wonderful!  Thanks so much!!!

**Comment by jasminb** [comment]
You are welcome, please close the issue in case you were able to solve your problem using suggestion above.

**Comment by bensullivan** [comment]
Thanks again!
