### ISSUE TITLE
When will release 1.0 be available?

### ISSUE THREAD

**Issue by thlaegler** [jasminb/jsonapi-converter#226]
Hi Friends,
Since your last release is already over a year ago I wanted to ask when there will be release 1.0?
The release would come with updated Jackson dependencies (seen in develop-branch) which we appreciate desperatly waiting for.

**Comment by jasminb** [comment]
Hello @thlaegler, 

Will try to create a release this week. Still have some PRs to merge...

**Comment by hamid646** [comment]
any updates on this?

**Comment by jasminb** [comment]
@hamid646 Ive just published version 0.10 of the lib. It is still not 1.0 but we are getting there.
