### ISSUE TITLE
@JsonProperty unexpectedly required

### ISSUE THREAD

**Issue by Human** [jasminb/jsonapi-converter#230]
I have a JSON object with a boolean `isFavorite` field, like so (simplified, obviously):

```
{ "attributes": { "isFavorite": false }}
```

If my kotlin class for parsing this object has an un-annotated `isFavorite` field, like so:

`var isFavorite: Boolean? = null`

The resulting object's `isFavorite` field remains null. However, if I _redundantly_ annotate it with `@JsonProperty` like so:

`@JsonProperty("isFavorite") var isFavorite: Boolean? = null`

it works as expected.

**Comment by pedrolaranjeiro** [comment]
I have exactly the same issue. I have an object with a `var isFavorite: Boolean` that is not parsed at all. @Human trick worked but why is this happening?

**Comment by jasminb** [comment]
This is related to how Jackson works and not to the lib.
