### ISSUE TITLE
How to configure ObjectMapper?

### ISSUE THREAD

**Issue by metschesd** [jasminb/jsonapi-converter#239]
Is there a way to configure Jackson's ObjectMapper which is used in the converter? I would like to ignore unkown properties like this:
```
ObjectMapper mapper = new ObjectMapper()
      .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

**Comment by metschesd** [comment]
Found it myself. Should have read the code earlier...

`resourceConverter = new ResourceConverter(mapper, ...);`

does the trick.

**Comment by jasminb** [comment]
Glad you were able to resolve it for yourself. Closing the issue.
