### ISSUE TITLE
Custom Object inside attributes is not parsed, it only allows String or List<String>

### ISSUE THREAD

**Issue by amanique** [jasminb/jsonapi-converter#24]
Hello,

I have an custom object inside attributes, which is not a relationship, that i can't parse.
If the variable is not a String or a List<>String>, is not parsed and returns null.
I give you an example:

JSON:

`{ 
    data: {
        id: 1,
        type: countries,
        attributes: {
            name: "France",
            capital: "Paris",
            location: {
                latitude: "46.1355292",
                longitude: "-2.2776085"
            }
        }
    }
}`

JAVA:

`@type("countries")
public class Country {
    
    @id
    public String id;

    public String name;

    public String capital;

    public Location location;

    public static class Location {
        
        public String latitude;

        public String longitude;

        public Location() {}
    }

    public Country() {}
}`

Thank you

**Comment by jasminb** [comment]
Hello,

Deserialisation/serialisation will work for objects of any complexity. Please check your classes/responses to make sure there't any typos or similar.

If you can provide exact responses, classes used and example on how the converter is instantiated I can provide more help.

Kind regards,
Jasmin

**Comment by amanique** [comment]
Hello thanks for the reply.
I'm sorry but i must call your attention again that this is not a relationship object, it's object inside attributes. Everything works fine on the example i gave you, name is parsed, capital is parsed, but location remains null.


```
public static ObjectMapper objectMapper = new ObjectMapper().configure
            (DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES, false).configure
            (DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

JSONAPIConverterFactory jsonapiConverterFactory = new JSONAPIConverterFactory(objectMapper, Country.class);
```

**Comment by jasminb** [comment]
Here is what i tried, and it works perfectly:

Input:

```
{
  "data" : {
    "id" : 1,
    "type" : "countries",
    "attributes" : {
      "name" : "France",
      "capital" : "Paris",
      "location" : {
        "latitude" : "123",
        "longitude" : "456"
      }
    }
  }
}
```

Class:

```
package com.github.jasminb.jsonapi.models;

import com.github.jasminb.jsonapi.annotations.Id;
import com.github.jasminb.jsonapi.annotations.Type;

@Type("countries")
public class Country {

	@Id
	public String id;

	public String name;

	public String capital;

	public Location location;

	public Country() {
	}

	public static class Location {

		public String latitude;

		public String longitude;

		public Location() {
		}
	}
}
```

Usage: 

```
ResourceConverter converter = new ResourceConverter(Country.class);
Country country = converter.readObject(input, Country.class);
Assert.assertEquals("123", country.location.latitude);
```

**Comment by amanique** [comment]
OK You are right, it worked. The problem was that the object had a private scope.
I tested with public and it worked, and then i tried private and a public setLocation() and it worked as well.
Maybe you would like to point this in the documentation.
Thank you.

**Comment by jasminb** [comment]
Hey,

Will update README with reference to jackson documentation.

Regards
