### ISSUE TITLE
How to handle class hierarchy?

### ISSUE THREAD

**Issue by joaofyz** [jasminb/jsonapi-converter#25]
Hi there,

How can we handle a situation where we want to receive a collection of objects, but with different sub-types? For instance a list of vehicles where we have, cars, bikes, trucks...

All the vehicles should have the same type: vehicle and we add an attribute "vehicle_type" or each one should have a different type (car, bike, truck)?

How can we handle each of the previous approaches with this library using Retrofit requests?

Thanks for your help

**Comment by jasminb** [comment]
Hello,

This is not related to the JSONAPI spec but rather to jackson library.

http://wiki.fasterxml.com/JacksonPolymorphicDeserialization

Regards

**Comment by joaofyz** [comment]
Thanks jasminb for your answer.

I was able to solve my problem with the @JsonTypeInfo and @JsonSubTypes annotations.

The only issue I identified was the need to have always de @Id annotation and field in every class even if it already exists in the Super class.

**Comment by jasminb** [comment]
Hey,

I've pushed a change today that solves the inheritance issue you are referring to.
If you use SNAPSHOT version of the library, it will work with inherited @Id field.

Regards

**Comment by joaofyz** [comment]
I do not use the SNAPSHOT version but I think you can close this issue.

Thanks for your help

**Comment by joaofyz** [comment]
Hi,

I'm having another problem with the hierarchical classes, now serializing the objects.

All my objects in JSONAPI are from the same type @Type("object_type"), but I can not have the same @Type annotation in the main and child classes. How can I do this?

Thanks

**Comment by jasminb** [comment]
Hey @joaofyz,

You cant inherit type (have multiple classes of the same type), however you can have a base class that has most of your attributes and than extend it and in subclasses to specify the type and additional attributes that you need.

When you deserialise you can do the following:

```
MyBaseClass object = resourceConverter.readDocument(data, MyBaseClass.class);

```
`object` will be instance of the correct subtype depending on the `type` attribute present in the `data`.

As for serialisation, no problem there, just `writeDocument` as usual.

**Comment by joaofyz** [comment]
I don't think this will solve my issue. Let me try to explain what I want to archive:

What I have now is the following:

One class Vehicle
`@Type("vehicle")
public class Vehicle {
...
}`

And a subclass Car
`@Type("car") // I need this to be "vehicle" also
public class Car {
...
}`

Thanks for the help again ;)

**Comment by jasminb** [comment]
Can you give more background on why would you want to have same type on multiple classes?

**Comment by joaofyz** [comment]
Hi @jasminb 

In the business prespective they are all "vehicles", so they are all mapped has vehicles.

Do you think I will be able to do this?

**Comment by jasminb** [comment]
Hey @joaofyz, if the API does not make a `type` difference between `Car` and `Vehicle` than your model should not do it.

What you can do is the following:
 - have one class that has all the attributes
 - create a factory that will create specific subclass depending on the attributes

Now I understand that these are design choices that you made for a reason, sadly it is not possible to create different object having same `type` attribute.
