### ISSUE TITLE
Get value above "attributes" level

### ISSUE THREAD

**Issue by Michigras** [jasminb/jsonapi-converter#253]
Hi,

I've got JSON data which looks like this (excerpt):

`"arbitrary": {
"data": {
"type": "arbitrary",
"id": "28",
"name": "Some Text"
}
}`

Is it possible to get access to the _name_ attribute?
I suppose it's an error and _name_ should be included inside an attributes object (as they correctly did in other parts of the JSON code).

**Comment by jasminb** [comment]
Hey there @Michigras,

Yes, `name` should be inside `attributes`.

You could fork and do some changes to be able to access the attribute, but IMHO the API should be fixed to be compliant with the spec.

**Comment by jasminb** [comment]
Closing as its asking about features not compatible with the spec.
