### ISSUE TITLE
Recursive loops may occur during resolution

### ISSUE THREAD

**Issue by emetsger** [jasminb/jsonapi-converter#28]
Models may introduce loops when resolving relationships:

@Type(...)
class Node {
  @Relationship(...)
  Node parent;
  // etc.
}

If the JSON for this Node has a parent relationship pointing to itself, the stack blows.

Even if the author makes poor modeling decisions, probably some protections should be put in place to avoid blowing the stack.

**Comment by jasminb** [comment]
@emetsger will take a look at this

PS
Sorry for late reply, was on vacation for a week

**Comment by emetsger** [comment]
@jasminb no apologies necessary, everyone needs a break once in a while!

**Comment by jasminb** [comment]
Been thinking about the issue and did review your resolution proposal.

I am thinking inline of having `ThreadLocal` cache that would be available trough entire response parsing lifecycle. This means that parser would reuse already parsed objects, eg:

If `A` is parsed once (`A` is identified by `id` and a `type`), it would be pushed to cache. 

When relationship is resolved and `JSON` object is retrieved, `identifier`  would be created and in case it is found in cache, cached object would be returned and hence no further pointers would be followed.

Now, `ThreadLocal` is kinda of overkill here but somehow having 2 versions of each method so just we can push cache around makes it more appealing to me.

**Comment by jasminb** [comment]
https://github.com/jasminb/jsonapi-converter/pull/34

**Comment by emetsger** [comment]
> Now, `ThreadLocal` is kinda of overkill here but somehow having 2 versions of each method so just we can push cache around makes it more appealing to me.

Thanks for considering my approach!  Using a `ThreadLocal` is fine with me!  Many thanks!

**Comment by jasminb** [comment]
Resolved.

**Comment by kishoresiri** [comment]
Row
{
@relational
Subtable subtable;
}

Subtable
{
@RelationShipLinks
List<Row> rowList;
}
Response
{
List<Row> rowList;
}

when i try to convert above response object  to JSON then josn object  is not containing any relationship / include....
how to resolve this issue?

**Comment by kishoresiri** [comment]
Row
{
@relational
Subtable subtable;
}

Subtable
{
@relationshiplinks
List<Row> rowList;
}
Response
{
List<Row> rowList;
}

when i try to convert above response object to JSON then josn object is not containing any relationship / include....
how to resolve relations ?
