### ISSUE TITLE
relationship of included data is null

### ISSUE THREAD

**Issue by fabricehong** [jasminb/jsonapi-converter#3]
Hi

the following example is not parsed correctly :
```
{
  ...

"included": [
    {
      "id": "1",
      "type": "office",
      "relationships": {
	"responsible_person": {
	  "data": {
	    "id": "10",
	    "type": "responsible_person"
	  }
	}
      },
      "attributes": {
	...
      }
    },
    {
      "id": "10",
      "type": "responsible_person",
      "attributes": {
	...
      }
    }
]
}
```

the office.responsible_person relationship will be null.

While parsing the object 'office' in method ResourceConverter.parseIncluded, it will call readObject to create office object with '(Map)null' as cache parameter. Having a null cache, 'handleRelationships' method won't be called to fill the object's relationships. even it a cache would be properly passed, the 'responsible_person' is not yet parsed in the while loop of ResourceConverter.parseIncluded.

It should be done in two phases I guess. One for creating objects, and one for filling them.

Can you confirm relationships in included data are not handled by the library ?

thanks !

**Comment by jasminb** [comment]
Hello,

You are correct, I will push a fix to support relationships in `included` resources.

**Comment by bartoslaw** [comment]
hey, how is it going with this issue? :) maybe you have some rough implementation, i'll be glad to help

**Comment by fabricehong** [comment]
Hi, I need to have that issue fixed today in my code. So same situation here :) either I make a quick fix, in my side, either I take your fix.
@bartoslaw : did you fork the repo somewhere so I can maybe use your fix ? 
@jasminb : Do you have an idea when the fix will be pushed ?. I'd be glad to also contribute. I would just need to know we you synchronize to avoid fixing the same issues

bests

**Comment by jasminb** [comment]
Hey, 

I will fix it today.

Jasmin

**Comment by bartoslaw** [comment]
@fabricehong unfortunately not yet ;)
@jasminb great, and just wanted to say thanks for this awesome lib! not enough android-friendly implementations of jsonapi parsers... (katharsis is such an overkill)

**Comment by jasminb** [comment]
Hey again,

Issue is fixed and pushed to develop.
Please give it a try and let me know.

Regards,
Jasmin

**Comment by fabricehong** [comment]
yep it works well !
thanks !
