### ISSUE TITLE
Meta attributes for resources in data collections

### ISSUE THREAD

**Issue by hndmrsh** [jasminb/jsonapi-converter#38]
First off, this is a super helpful library, thanks so much for the work you've put in so far.

At the moment the `meta` field on data objects is not supported as part of the JSON deserialization. Issue #15 discusses the missing `meta` field on the collection itself, but this does not address the lack of `meta` attributes on the individual resources within a collection, such as the following JSON:

```
{
  "data": [
    {
      "id": "1",
      "type": "check_ins",
      "attributes": {
        ...
      },
      "relationships": {
        ...
      },
      "links": {
        ...
      },
      "meta": {
        "is_me": false,
        "is_friend": false,
        "has_liked": true,
        "has_commented": false,
        "comments_count": 1,
        "likes_count": 2
      }
    },
    ...
  ],
  "included": [
    ...
  ],
  "links": {
    ...
  }
}
```

As a temporary workaround, I have checked out @emetsger's `develop-wip` branch. That PR goes most of the way to solving this issue, except that the call to `readObjectInternal` does not parse the `meta` field. To address this, I copied the following block of code:

```
// handling of meta node
if (source.has(META)) {
	Field field = META_FIELD.get(clazz);
	if (field != null) {
		Class<?> metaType = META_TYPE_MAP.get(clazz);
		Object metaObject = objectMapper.treeToValue(source.get(META), metaType);
		field.set(result, metaObject);
	}
}
```

... from the method `readObjectInternal(byte [] Class<T>, ResolverState)` to `readObjectInternal(JsonNode, Class<T>, Map<String, Object>, ResolverState)`.

Let me know if you have any questions!

**Comment by hndmrsh** [comment]
Regarding the workaround using @emetsger's PR: the workaround does not successfully deserialize Snake Case to Camel Case fields (so does not deserialize the `is_friend` attribute to my `isFriend` field on my model).

**Comment by emetsger** [comment]
@hndmrsh 

> Solved this issue: it was due to not having setters for the boolean fields. Were you aware this was required?

No, I didn't realize that setters were required. Are you using the `@Meta` annotation from my `develop-wip` branch in concert with the setters, or did you use the vanilla `develop` branch in concert with setters? 

Another alternative that may work, which I haven't tried, is to use some Jackson magic to deserialize the `meta` member in your JSON (`@AnySetter`?).

**Comment by hndmrsh** [comment]
@emetsger 

The setters were used for boolean fields inside my `@Meta`-annotated models, which were based on your `develop-wip` branch.

The `@AnySetter` approach is interesting, and that could very well work as a workaround also. If I have time to investigate it today, I will look into it.

With regards to the original issue of not being able to access metadata for objects within a collection: are you likely to address this at some point in your `develop-wip` branch?

Thanks very much for your contributions to this project so far 😄

**Comment by jasminb** [comment]
Hey @hndmrsh please check #41 and close the issue.
