### ISSUE TITLE
Does not handle "data": null

### ISSUE THREAD

**Issue by shanemmurphy30** [jasminb/jsonapi-converter#4]
I experience an exception when a relationship has a null data field.

Example
 relationship: {"links":{"self":"http://www.test.com","related":"http://www.test.com"},"data":null}

Exception:
Attempt to invoke virtual method 'java.lang.String com.fasterxml.jackson.databind.JsonNode.asText()' on a null object reference

It seems to treat data value as a string "null" and not as null value.

**Comment by jasminb** [comment]
Hello,

It appears I missed it in the spec, it states that relationship can exists with either links or data nodes. I will fix the issue.

Thanks for reporting it,
Jasmin

**Comment by bartoslaw** [comment]
hey, we came across the same bug, for now we're using this workaround:

```
if(!(dataObject instanceof NullNode)) {
    String identifier = createIdentifier(dataObject);
    if (includedData.containsKey(identifier)) {
        relationshipField.set(object, includedData.get(identifier));
    } else {
        Object relationshipObject = readObject(dataObject, type, includedData);
        relationshipField.set(object, relationshipObject);
    }
}
```

please keep in mind that it's just a temporary workaround, didn't have time yet to work on proper solution :)

**Comment by jasminb** [comment]
Hello again,

I've fixed the issue and pushed to `develop`.

Relationship objects will be validated before parse attempt is made.

In case relationship is missing 'data' node or `data` node is missing either `id` or `type`, relationship will be skipped.

Please have in mind that in case relationship is missing `data` node but does have `links` node with `self` populated, and relationship `resolver` is registered, link will be used and relationship object will be created.

Regards,
Jasmin
