### ISSUE TITLE
is "included" required? 

### ISSUE THREAD

**Issue by peavers** [jasminb/jsonapi-converter#42]
I'm having issues trying to read in a basic object. 

It looks like a null pointer is being thrown inside the readObject right at 
```
T result = readObject(dataNode, clazz, included);
```
Due to included being null... 

Using a very simple demo app, and posting the follow request
```
{
  "data": {
    "type": "server",
    "attributes": {
      "nameTag": "sample project"
    }
  }
}
```
As [include](http://jsonapi.org/format/#document-top-level) isn't a requirement according to the spec, is there something else I'm doing wrong here?

**Comment by jasminb** [comment]
Hey,

It looks like you are missing the `id` attribute (id and type must be present).

**Comment by peavers** [comment]
Ha that solved it, not sure how I missed the obvious. Cheers for all the awesome work!

**Comment by peavers** [comment]
Sorry, I'm back...

Do you have a suggestion/example for how I could generate the id server side for new objects rather than in the client? I'm consuming the incoming Json request as a string and can't think of a clean way to manage this.

**Comment by jasminb** [comment]
Hey,

Is the server side something that you control?

Usually resources are assigned ids when they are stored to permanent store (this can be RDBMS/NoSQL or any other storage implementations.

Generated id than is used to fetch resource using the id value.

If you are using Long/Integer as your primary key in database, you can convert it to `String` for sakes of compatibility with JSON API Spec.

Have in mind that all of these are wild guesses since I am not familiar with what you are trying to build and how you are building it.

Regards

**Comment by peavers** [comment]
Yup, full control over the backend (Using Dropwizard and MongoDB). This is where I tripped up with my previous message as I was used to the IDs being generated on the fly using an ObjectID (from bson). Which obviously meant I didn't need to pass an ID when creating the object for the first time.   

I guess to rephrase my latest message if I must pass an ID in the request, even if the object isn't created yet it makes things awkward. From what I can tell, your library fails with a null pointer if I don't include the ID, which doesn't yet exist as the object isn't written to the database or even initialized?. Would it not be possible to create an instance of the object before checking for the ID, therefore allowing the objects constructor to assign the ID as needed? 

Or do you have an example of using MongoDB and creating new objects from requests? 

Appreciate the help :)

**Comment by jasminb** [comment]
Hey,

Just to make it clear, are you using the client to send requests to a server or go deserialise responses received from the server.

In case you are getting information from the server and trying to deserialise, `id` must be present (if resource was fetched from the server it must have an id set or else it should not exist on the server in the first place).

If you using the client to execute `POST` request (to create a new resource) than `id` can be omitted and object will be correctly serialised without id.

Regards,
Jasmin

**Comment by peavers** [comment]
It's creating the object from the client via POST that is causing issues. If I send a POST request without the ID attribute I get the null pointer thrown at:

```public <T> T readObject(byte[] data, Class<T> clazz) { 
[...]
}
```
From what I can work out because it's calling: 
```
    private String createIdentifier(JsonNode object) {
        String id = object.get("id").asText();
        String type = object.get("type").asText();
        return type.concat(id.toString());
    }
```

and ```object.get("id")``` is failing as there is no ID, hence the null pointer?

**Comment by jasminb** [comment]
I dont understand how do you perform the POST request using the client and `readObject` method, you should be using `writeObject` to get the bytes and then post it to the server?

**Comment by peavers** [comment]
Hmm let me try showing what I'm doing

ServerResource.class
```
	@POST
	 public Response save(String payload) {
	    return Response.status(Response.Status.ACCEPTED).entity(repository.save(payload)).build();
	}
```
So my request from the client (EmberJS frontend) comes into the server here as a POST request. This is on the assumption that no Server object exists in the database, hence no ID. 

Here is the save method from the repository class
```
	public String save(String payload) {
		Server server = converter.readObject(payload.getBytes(), Server.class);
		Key<Server> savedServer = datastore.save(server);
		Server byKey = datastore.getByKey(Server.class, savedServer);

		try {
			return new String(converter.writeObject(byKey), StandardCharsets.UTF_8);
		} catch (JsonProcessingException | IllegalAccessException e) {
			LOGGER.debug(e.getMessage());
		}

		return null;
	}
```
The first line, Server server = converter[...] returns the null pointer if no ID is set in the payload. 

Have I got things completely backwards?

**Comment by jasminb** [comment]
Ah, ok than, you are using the client on the server side to deserialise payloads coming from clients.

Simple workaround for you would be to simply send blank `id` field as part of the payload sent to server and than populate the actual id on the server side.

Allowing deserialisation of resources without id is messy since type/id combination is used to uniquely identify a resource during deserialisation of collection of resources or of resources with relationships or included section.

**Comment by jasminb** [comment]
Hey,

I've added concept of `Deserialisation options` to the resource converted.

You can do the following to avoid having NPE when no id is present:

```
ResourceConverter converter = new ...
converter.disableDeserialisationOption(DeserializationFeature.REQUIRE_RESOURCE_ID);

```

This allows you to remove id restriction.

Have in mind that this is on 'develop' branch, so you must checkout the code, build develop branch and use it as a dependency.

Alternative would be for you to use current snapshot version (see README file).

**Comment by peavers** [comment]
Ha before I saw this I had just written a similar solution, but this is heaps cleaner. Thank you very much it all works as expected and makes my life heaps easier! 

Cheers again!

**Comment by jasminb** [comment]
Np, glad I could help.
