### ISSUE TITLE
Links are not working for relationships

### ISSUE THREAD

**Issue by kotak25krishna** [jasminb/jsonapi-converter#44]
I tried with 0.3 version to Marshal the resources in the below json response

{
  "type": "articles",
  "id": "1",
  "attributes": {
    "title": "Rails is Omakase"
  },
  "relationships": {
    "author": {
      "links": {
        "self": "/articles/1/relationships/author",
        "related": "/articles/1/author"
      },
      "data": { "type": "people", "id": "9" }
    }
  }
}

However I am not able to generate "links" object with self and related members. Is that not available in 0.3. Is there any plan to include them in next version

**Comment by jasminb** [comment]
Hello,

Please provide your model classes, if annotated properly, it should work.

**Comment by kotak25krishna** [comment]
Attached the resource objects and test client. 
[Links_Not_Working.docx](https://github.com/jasminb/jsonapi-converter/files/326898/Links_Not_Working.docx)

**Comment by kotak25krishna** [comment]
Hi, All I am trying is to convert Resource classes to json.
As per the documentation (README.md) it seems JSONAPIDocument is for unmarshalling. I have tried  using this JSONAPIDocument , however i couldn't find a way to extract json from the Resource class.
If the way I understood the API is wrong, please let me know.

**Comment by jasminb** [comment]
Hey,

If you need to `marshal` resource objects into JSON API spec format, use:

```
byte [] rawData = converter.writeObject(book);

// If String is required
String marshalled = new String(rawData, StandardCharsets.UTF_8);
```

Please have in mind that for marshalling you need to pass actual resource objects rather than 
`JSONAPIDocument`.

**Comment by kotak25krishna** [comment]
Thanks. I have built the logic to obtain links for relationships, which is tested and found to be working. I am not able to attach here for sharing. Let me know if there is any alternative way to share. 
See if it can be released into 0.4.
Please let me know.

**Comment by jasminb** [comment]
Hey,

You can fork this repo, make the changes, push to github and than create a PR.

**Comment by uddyami** [comment]
is there any update for this? I'm trying something similar and seems like links for included object didn't come through.

**Comment by jasminb** [comment]
Hey @uddyami, can you please present the exact issue you are having and version of the lib?

**Comment by uddyami** [comment]
The `Links` section cannot be custom identifier it seems to me. The `next` and `self` gets serialized way but custom tags `icon` and `front` were ignored. Any ideas how to allow for custom tags in link section?

**Comment by jasminb** [comment]
Hey @uddyami, issue is fixed and pushed to `develop`. You can either checkout latest code or use `snapshot` version to check it out.

**Comment by uddyami** [comment]
Thank you for the quick turn around.. it working perfectly now :)

**Comment by aravind6941** [comment]
Hi, 
Below is my jsonapi response. I am unable to parse the relationship links. I am using jsonapi-converter 0.3 version. 

{
  "data": {
    "type": "objects",
    "id": "id",
    "attributes": {
      "title": "title"
    },
    "relationships": {
      "workplaces": {
        "links": {
          "self": "http://myserviceurl",
        }
      }
    }
   "links":{
      "self": "http://myserviceurl"
    }
  },
  "included": []
}

Thanks,
AJ

**Comment by jasminb** [comment]
Hello, Please switch to using latest version (`0.4`), also, payload you provided is not a valid JSON.

**Comment by aravind6941** [comment]
Hi,

Below is the exact jsonapi response.  I need to retrieve the links of self and related present in the "folders". 

Response : {
	"data":[
		{
			"type" : "myprojects",
			"id"   : "project12345",
			"attributes": {
				"created_time" : "Aug 2016",
				"name"         : "educational stratgies"
			},
			"relationships": {
				"folders" : {
				 "links": {
				   	"self" : "/myprojects/projects12345/relationships/folders",
					"related" : "/myprojects/project12345/folders"
					}
			 }
			 },
			 "links": {
				"self": "/myprojects/project12345"
			 }
		  }
		],
		"included": []
}

I have not tried with 0.4, still using 0.3, is it possible to read the same.

**Comment by jasminb** [comment]
Fixed.
