### ISSUE TITLE
Included is not available for related resources while serializing.

### ISSUE THREAD

**Issue by r4ram** [jasminb/jsonapi-converter#45]
Hi,
I tried to serialize 2 related resources with the 0.3 version, but the relation is only available with the type and id. The attributes of the relation which will be available in included is not getting displayed.

Actual Result,
`{
    "data": {
        "type": "mainResponse",
        "id": "3",
        "attributes": {
            "emp-id": "456879",
            "name": "John",
            "sub-response": {
                "id": "2",
                "ph-no": "1234569778",
                "vnet": "156478"
            },
        },
        "relationships": {
            "subResponse": {
                "data": {
                    "type": "subResponse",
                    "id": "2"
                }
            }
        }
    }
}
`

POJO classes,
[MainResponse.txt](https://github.com/jasminb/jsonapi-converter/files/329687/MainResponse.txt)
[SubResponse.txt](https://github.com/jasminb/jsonapi-converter/files/329688/SubResponse.txt)

**Comment by jasminb** [comment]
Hello,

As per my understanding of JSON API specification, serialisation should not include relationship attributes since you cannot create relationship objects implicitly.

What this means that, if you have two different resources for creation, you first need to create related one and than create base one referencing the one you just created.

In your case:

 - create sub resource first
 - create main resource referencing the sub resource

**Comment by r4ram** [comment]
Thanks, But i have problem in generating the meta info. When I use the @meta attribute to display my meta data its getting hidden in the response. Do I need to do any additional configuration other than the meta attribute?

**Comment by jasminb** [comment]
Hey,

Can you provide sample response with meta in it.

There are two levels where meta can occur:
 - resource level (that is handled by the `@Meta` annotated attribute you already did)
 - response level (that is returned as part of JSONAPIDocument if you are using non-deprecated `readDocument` or `readDocumentCollection` methods

**Comment by r4ram** [comment]
The problem is that i'm not able to write the meta data in the json response. 

response with the hidden meta.
{
    "data": {
        "type": "users",
        "id": "123",
        "attributes": {
            "name": "John Nash"
        }
    }
}
[json api meta.txt](https://github.com/jasminb/jsonapi-converter/files/331372/json.api.meta.txt)

Attached my approach of generating the meta data.

**Comment by jasminb** [comment]
So, initially library was not created to be used on server side for generating responses (serialisation).

As this is something that is useful to folks that do not want to use more complex frameworks to achieve JSON API spec compliance I will work on extending the lib as part of 0.4 that will provide you with options to enable meta and full relationship serialisation.

**Comment by r4ram** [comment]
Thanks, waiting for your update. 
what is the expected date of the next release?

**Comment by jasminb** [comment]
I will probably be able to push something today on dev branch, you could try using 0.4-SNAPSHOT afterwards. Will update you when done.

**Comment by r4ram** [comment]
How to implement custom errors while building the json resoponse. I'm following the same approach which has been uploaded already.

**Comment by wmcdona89** [comment]
Very interested in using this library server side. Looking forward to improved serialization support!

**Comment by peavers** [comment]
Also interested in how I can included ```included``` values in my response.

**Comment by jasminb** [comment]
I've pushed changes that allow for enabling the generation of `included` data section during serialisation.

In order to enable it:

```
converter.enableSerializationOption(SerializationFeature.INCLUDE_RELATIONSHIP_ATTRIBUTES);
```

Also, related to one of the first comments here, library now fully supports handling all meta-data (both resource level and global).

Please consider closing the issue after review.

**Comment by jasminb** [comment]
Fixed.
