### ISSUE TITLE
Consider katharsis.io annotation support

### ISSUE THREAD

**Issue by remmeier** [jasminb/jsonapi-converter#47]
http://katharsis.io is a server-side jsonapi implementation. It would be great if katharsis and this project could agree on a common set of annotations so that classes do not need to be annotated for both libraries seperately if both client and server are written in Java. I created a ticket here to start.

**Comment by remmeier** [comment]
Maybe a related topic. It would be great to have further support in Retrofit. For example:
:
@JsonApiResourceRepository
interface UserRepository {
Call<List<User>> findAll(QueryParams params);
...
}

UserRepository repo = retrofit.create(UserRepository.class);
repo.findAll(queryParams);

I reused here QueryParams  and JsonApiResourceRepository from karthesis. QueryParams allows to to specify sorting, filtering, paging, etc.

I had a look at the retrofit implementation. I think a new retrofit2.ServiceMethod.Builder needs to be implemented that does the JSON API parameter/annotion handling. Retrofit is currently not yet that flexible in this regards. So that needs to change or other classes like Retrofit itself would need to be subclassed and adapter accordingly. Effort to get something up and running should be quite small.

**Comment by peavers** [comment]
Since the Katharsis has now been abandoned, this can probably be closed.
