### ISSUE TITLE
Errors parsing

### ISSUE THREAD

**Issue by fabricehong** [jasminb/jsonapi-converter#5]
Hi

the error handling seems to be not implemented yet. Is it something you planned ?

http://jsonapi.org/format/#errors

**Comment by jasminb** [comment]
Hello,

You are correct. Error responses are not handled currently.

I will add it as soon as possible.

Regards,
Jasmin

**Comment by jasminb** [comment]
Hey,

I've pushed initial error handling implementation.

Please see updated README file for details on how to use it with Retrofit.

Regards,
Jasmin

**Comment by fabricehong** [comment]
It works well. ErrorUtils is very handy.

However, the Error class conflicts with java.lang.Error. As a consequence, the whole package name have to be written in every declarations.

**Comment by jasminb** [comment]
I don't see a problem with naming. Usually `java.lang.Error` is not caught in catch blocks (should not go above `Exception`).

Regards,
Jasmin

**Comment by fabricehong** [comment]
you're right. I was an IDE problem.
thx
