### ISSUE TITLE
Bulk resource creation

### ISSUE THREAD

**Issue by bmin** [jasminb/jsonapi-converter#54]
I was trying to create multiple resources in one go, but failed to do so. Following test case with attached data failed (data where there is not "ID" provided for resources).

```
		converter.disableDeserializationOption(DeserializationFeature.REQUIRE_RESOURCE_ID);
		String rawData = IOUtils.getResourceAsString("users-no-id.json");
		List<User> users = converter.readDocumentCollection(rawData.getBytes(StandardCharsets.UTF_8), User.class).get();
		Assert.assertNotNull(users);
		Assert.assertEquals(2, users.size());
		Assert.assertEquals("liz", users.get(0).getName());
		Assert.assertEquals("john", users.get(1).getName());

```
ResourceConverter's createIdentifier(...) returns same identification (which is actually type of the resource) for every resources; thus ResourceCache provides same resource again.

[users-no-id.txt](https://github.com/jasminb/jsonapi-converter/files/373917/users-no-id.txt)

**Comment by jasminb** [comment]
Hey,

As per specification:

```
Creating Resources

A resource can be created by sending a POST request to a URL that represents a collection of resources. 
The request MUST include a single resource object as primary data. 
The resource object MUST contain at least a type member.
```

As per specification (and my experience), you should never try to create multiple resources in one request. 

Your motivation is probably to mitigate network overhead by you usually can go around it by introducing parallelism into your client implementation (total duration would still end up being equal to slowest single resource create request).

**Comment by bmin** [comment]
Thank you for quick response. I have checked the specification. I have both implementation in hand, user can send single or multiple resources to a resource collection - hoping that they will include something that I need in future. Anyway, I have workaround similar to what you said, so will keep it until {json:api} specification as well as your implementation gets changed :D Thank you.

**Comment by jasminb** [comment]
YW, can you please close the issue.
