### ISSUE TITLE
Annotated @Links object is not serializing correctly

### ISSUE THREAD

**Issue by Kylar42** [jasminb/jsonapi-converter#56]
I've defined an entity that is annotating and adding a property annotated Links object, and when serializing, the output has:

1) The links inside the attributes{} object, instead of at the top level, as shown in the spec: http://jsonapi.org

2) It's duplicating the links object inside there, incorrectly.

3) The links object is serializing a meta object, incorrectly.

Code:
`

    import com.github.jasminb.jsonapi.JSONAPISpecConstants;
    import com.github.jasminb.jsonapi.Link;
    import com.github.jasminb.jsonapi.ResourceConverter;
    import com.github.jasminb.jsonapi.annotations.Id;
    import com.github.jasminb.jsonapi.annotations.Links;
    import com.github.jasminb.jsonapi.annotations.Type;

    import java.util.HashMap;
    import java.util.Map;

    @Type("dragon")
    public class EntityWithLinks {

    @Id
    public String id = "TROGDOR-ABC";

    @Links
    public com.github.jasminb.jsonapi.Links links;

    public String otherInfo = "TROGDOR COMES IN THE NIGHT";

    public String getOtherInfo() {
        return otherInfo;
    }

    public void setOtherInfo(String otherInfo) {
        this.otherInfo = otherInfo;
    }

    public EntityWithLinks(){
        Map<String, Link> linksMap = new HashMap<>();
        linksMap.put(JSONAPISpecConstants.SELF, new Link("http://www.homestarrunner.com/sbemail58.html"));
        links = new com.github.jasminb.jsonapi.Links(linksMap);
    }
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
    public static void main(String[] args) throws Exception{
        ResourceConverter converter = new ResourceConverter(EntityWithLinks.class);
        byte[] bytes = converter.writeObject(new EntityWithLinks());
        System.out.println(new String(bytes));
    }

    }
`

and the output (made pretty)

```json
{
	"data": {
		"type": "dragon",
		"id": "TROGDOR-ABC",
		"attributes": {
			"links": {
				"links": {
					"self": {
						"href": "http://www.homestarrunner.com/sbemail58.html",
						"meta": {
						}
					}
				},
				"self": {
					"href": "http://www.homestarrunner.com/sbemail58.html",
					"meta": {
					}
				}
			},
			"otherInfo": "TROGDOR COMES IN THE NIGHT"
		}
	}
}

```

**Comment by Kylar42** [comment]
The resulting JSON entity should look like this:

```json

{
	"data": {
		"type": "dragon",
		"id": "TROGDOR-ABC",
		"links": {
			"self": "http://www.homestarrunner.com/sbemail58.html"	
		},
		"attributes": {
			"otherInfo": "TROGDOR COMES IN THE NIGHT"
		}
	}
}
```

**Comment by jasminb** [comment]
Hey @Kylar42,

I've fixed the issue you reported. Please note that `links` serialisation must be explicitly enabled:

```
		converter.enableSerializationOption(SerializationFeature.INCLUDE_LINKS);
```

Method you were using is deprecated now, new method is added:

```
public byte [] writeDocument(JSONAPIDocument<?> document) throws DocumentSerializationException  {}
```

**Comment by Kylar42** [comment]
Is there a doc update that shows how to use the "new" serialization methods? And when do you expect to release a new version with this fix? (I'm using 0.4-Snapshot).

**Comment by jasminb** [comment]
Hey,

One more standing issue exists (generating `included` data during serialisation), after that one is finished I will update docs and do a `0.4` release.

**Comment by jasminb** [comment]
Documentation updated and `0.4` released, check it out and please close the issue.

**Comment by Kylar42** [comment]
I will test it this week, thanks!

**Comment by Kylar42** [comment]
Looks great, thanks!
