### ISSUE TITLE
gradle dependency for snapshot not working 

### ISSUE THREAD

**Issue by uddyami** [jasminb/jsonapi-converter#58]
```
Error:Could not find com.github.jasminb:jsonapi-converter:0.4-SNAPSHOT.
Required by:
    :app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

build.gradle
```
repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/"}
    }

dependencies{
 compile 'com.github.jasminb:jsonapi-converter:0.4-SNAPSHOT'
}
```

**Comment by jasminb** [comment]
Hey @uddyami, just checked using maven project and it works without issue.

By manually checking repo URL: https://oss.sonatype.org/content/repositories/snapshots/com/github/jasminb/jsonapi-converter/0.4-SNAPSHOT/, you can verify that its there.

Please check your gradle configuration.

**Comment by uddyami** [comment]
I checked the link.. it works but for some reason i cannot get it for grade.. i'll check again in build.gradle

**Comment by uddyami** [comment]
i found the problem in my build.gradle
