### ISSUE TITLE
Error when parsing null primary data

### ISSUE THREAD

**Issue by hndmrsh** [jasminb/jsonapi-converter#59]
I am trying to retrieve a resource from an endpoint which may or may not exist (where not existing is a valid state). When the resource does not exist, the following object is returned:

```
{
  "data": null
}
```

According to the JSON-API spec, this is valid (["Primary data MUST be... a single resource object, a single resource identifier object, **or null**, for requests that target single resources"](http://jsonapi.org/format/#document-top-level)). However, deserialization of this object fails with the error: "'data' node cannot be simple attribute!".

**Comment by jasminb** [comment]
Hey @hndmrsh ,

Thanks for reporting it.

As I understand the spec, lib should produce `null` result in this case (`JSONAPIDocument.get() == null`)?

**Comment by hndmrsh** [comment]
Hi,

Yes, that is what I would expect also. The same would go for cases where `JSONAPIDocument` is not used; for example, a `Response<MyModel>` object would return `null` for `body()`.

**Comment by jasminb** [comment]
Hey,

Issue is resolved and pushed to `develop`.

`JSONAPIDocument<Type>.get()` will return `null`
`JSONAPIDocument<List<Type>>.get()` will return empty collection.

**Comment by hndmrsh** [comment]
Hey - cool, this seems to work well. Thanks!
