### ISSUE TITLE
Maven package

### ISSUE THREAD

**Issue by ghn** [jasminb/jsonapi-converter#6]
Hello,
nice work. It'd be great to have this package pushed on maven central repository :+1:

**Comment by jasminb** [comment]
Hey,

I've already opened JIRA ticket on Sonatype in order to get the group id approved and start the process of publishing. Will update this ticket when the process is completed.

Regards,
Jasmin

**Comment by jasminb** [comment]
Project is available on maven central, to use it:

```
##### Including the library in your project

```
<dependency>
  <groupId>com.github.jasminb</groupId>
  <artifactId>jsonapi-converter</artifactId>
  <version>0.2</version>
</dependency>
```
```

**Comment by saigyo** [comment]
Cool! 
Keep up the good work!
