### ISSUE TITLE
Pls give latest set of  jars list  to compile jsonapi convertor base, I am not using maven,i tried with following jar , but getting exceptions while executing an  file

### ISSUE THREAD

**Issue by pradeepmallika** [jasminb/jsonapi-converter#60]
I am using the below listed jars

jackson-annotations-2.0.1.jar
jackson-core-2.5.0.jar
jackson-databind-2.7.1.jar
jsonapi-converter-0.3.jar
junit-4.12.jar
mockwebserver-3.0.0.jar
okhttp-1.2.0.jar
okhttp-2.7.5.jar
okhttp-3.2.0.jar
retrofit-2.0.1.jar

I am getting following exception trace

> java -cp .:lib/*:  com/github/jasminb/jsonapi/ResourceConverterTest
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonInclude$Value
	at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:45)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:535)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:452)
	at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:65)
	at com.github.jasminb.jsonapi.ResourceConverter.<init>(ResourceConverter.java:50)
	at com.github.jasminb.jsonapi.ResourceConverterTest.main(ResourceConverterTest.java:33)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonInclude$Value
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)

Pls help me to fix the problem.

**Comment by jasminb** [comment]
Hey,

Here are the dependencies:

com.squareup.retrofit2:retrofit:jar:2.1.0
com.squareup.okhttp3:okhttp:jar:3.3.0
com.squareup.okio:okio:jar:1.8.0
com.fasterxml.jackson.core:jackson-databind:jar:2.7.1
com.fasterxml.jackson.core:jackson-annotations:jar:2.7.0
com.fasterxml.jackson.core:jackson-core:jar:2.7.1

**Comment by pradeepmallika** [comment]
Problem solved, thank you @jasminb :)

**Comment by pradeepmallika** [comment]
RetrofitTest.java  is not compiling , other than  RetrofitTest.java   all other files is compiling

> /java/com/github/jasminb/jsonapi/retrofit/RetrofitTest.java:9: error: package okhttp3.mockwebserver does not exist
import okhttp3.mockwebserver.MockResponse;


I tried to include mockwebserver-3.0.0.jar

Mockserver compilation problem solved  but  i am getting below exception while compiling 

> ./java/com/github/jasminb/jsonapi/retrofit/RetrofitTest.java:42: error: cannot access Converter
		Retrofit retrofit = new Retrofit.Builder().baseUrl(server.url("/").toString()).addConverterFactory(converterFactory).build();
		                                                                              ^
  class file for retrofit.Converter not found
./java/com/github/jasminb/jsonapi/retrofit/RetrofitTest.java:99: error: cannot access ResponseBody
		ErrorResponse errorResponse = ErrorUtils.parseErrorResponse(response.errorBody());
		                                        ^


Pls help me to fix this compiler exception, List of jars used by me

> jackson-annotations-2.7.0.jar
jackson-core-2.7.1.jar
jackson-databind-2.7.1.jar
jsonapi-converter-0.3.jar
junit-4.12.jar
mockwebserver-3.0.0.jar
okhttp-3.3.0.jar
okio-1.8.0.jar
retrofit-2.1.0.jar

**Comment by pradeepmallika** [comment]
RetrofitTest.java  is not compiling , other than  RetrofitTest.java   all other files is compiling

> /java/com/github/jasminb/jsonapi/retrofit/RetrofitTest.java:9: error: package okhttp3.mockwebserver does not exist
import okhttp3.mockwebserver.MockResponse;


I tried to include mockwebserver-3.0.0.jar

Mockserver compilation problem solved  but  i am getting below exception while compiling 

> ./java/com/github/jasminb/jsonapi/retrofit/RetrofitTest.java:42: error: cannot access Converter
		Retrofit retrofit = new Retrofit.Builder().baseUrl(server.url("/").toString()).addConverterFactory(converterFactory).build();
		                                                                              ^
  class file for retrofit.Converter not found
./java/com/github/jasminb/jsonapi/retrofit/RetrofitTest.java:99: error: cannot access ResponseBody
		ErrorResponse errorResponse = ErrorUtils.parseErrorResponse(response.errorBody());
		                                        ^


Pls help me to fix this compiler exception, List of jars used by me

> jackson-annotations-2.7.0.jar
jackson-core-2.7.1.jar
jackson-databind-2.7.1.jar
jsonapi-converter-0.3.jar
junit-4.12.jar
mockwebserver-3.0.0.jar
okhttp-3.3.0.jar
okio-1.8.0.jar
retrofit-2.1.0.jar

**Comment by jasminb** [comment]
Hey,

Heres the list including test dependencies:

```
com.squareup.retrofit2:retrofit:jar:2.1.0
com.squareup.okhttp3:okhttp:jar:3.3.0
com.squareup.okio:okio:jar:1.8.0
com.fasterxml.jackson.core:jackson-databind:jar:2.7.1
com.fasterxml.jackson.core:jackson-annotations:jar:2.7.0
com.fasterxml.jackson.core:jackson-core:jar:2.7.1
junit:junit:jar:4.12:test
org.hamcrest:hamcrest-core:jar:1.3:test
com.squareup.okhttp3:mockwebserver:jar:3.2.0:test
com.squareup.okhttp3:okhttp-ws:jar:3.2.0:test
org.bouncycastle:bcprov-jdk15on:jar:1.50
```

**Comment by pradeepmallika** [comment]
I added all the jars mention by you, Still getting the following exception

> ./java/com/github/jasminb/jsonapi/retrofit/RetrofitTest.java:42: error: cannot access Converter
		Retrofit retrofit = new Retrofit.Builder().baseUrl(server.url("/").toString()).addConverterFactory(converterFactory).build();
		                                                                              ^
  class file for retrofit.Converter not found
./java/com/github/jasminb/jsonapi/retrofit/RetrofitTest.java:99: error: cannot access ResponseBody
		ErrorResponse errorResponse = ErrorUtils.parseErrorResponse(response.errorBody());
		                                        ^
  class file for com.squareup.okhttp.ResponseBody not found

**Comment by jasminb** [comment]
What kind of project do you have, why not just use sbt/maven?

**Comment by pradeepmallika** [comment]
@jasminb   I have downloaded  jsonapi-converter(zip i got is jsonapi-converter-22c0f26ac08206737fbbee59a593ff4f5d18791f.zip) from git hub and compiling in terminal

**Comment by jasminb** [comment]
You should use current `develop` branch, what you downloaded has number of issues that were resolved on `develop` (dependencies I provided are for current develop).

Instead of downloading, you can install `git` and perform a `clone` using `https` if you do not have your keys setup.

Let me know if you need anything else.
