### ISSUE TITLE
Whether it is possible to use two  @Type ( i.e @Type("users") ,@Type("articles") ) in a model file 

### ISSUE THREAD

**Issue by pradeepmallika** [jasminb/jsonapi-converter#61]
@jasminb 
because my type value is only different but the values inside is same , if it not, whether any alternative way is there, to avoid duplicate the model file except the @Type variation 

Pradeep

**Comment by jasminb** [comment]
You can make a base class and than extend it two times and annotate with differently configured `Type` annotation.

**Comment by pradeepmallika** [comment]
@jasminb   Thank you, your solution worked.
