### ISSUE TITLE
ResourceConverter should allow deserializing arbitrary JSON-API–compliant objects

### ISSUE THREAD

**Issue by hndmrsh** [jasminb/jsonapi-converter#64]
Hi,

To my knowledge, the only way to deserialize a JSON-API object with a ResourceConverter  at the moment is to use the `readDocument(byte[], Class)`. This requires prior knowledge of the type of object to be deserialized - this can sometimes be an issue, as it is not always possible to know what type of object we are expecting. For example, my Android client is registered to receive push notifications, which can be one of several types. Given that `@Type`-annotated models exist to deserialize each of these types (and are registered with the ResourceConverter), it would be nice to be able to use the ResourceConverter to determine which model the object should be deserialized into rather than having to work it out manually in advance.

Thoughts?

**Comment by jasminb** [comment]
Hey,

New method could be made available that will use the 'type' attribute in order to resolve the what object to create. Problem here is that it's signature would be 'JSONAPIDocument<?> which could confuse users and move them toward using it even when not appropriate since its signature is less strict.

**Comment by hndmrsh** [comment]
What if there was a method in the ResourceConverter which could be used in conjunction with `readDocument` rather than replaces it (i.e. it returns the Class of the model represented by the byte[] array/input stream)? This way it does not overload the `readDocument` method, so it should not inadvertently encourage users to use it over the existing method.

At the moment I am having to do the following to determine the type (which is not ideal):
```
JSONObject jsonObject = new JSONObject(jsonString);
String type = jsonObject.getJSONObject("data").getString("type");
```

**Comment by jasminb** [comment]
Hey,

It could be added but it brings overhead of having to parse actual JSON to extract the `type` value.

However, since it is a `helper` method and used for edge cases, I think it is acceptable solution.

We would end up having something like this:

```
Class<?> type = converter.getType(responseData);
JSONAPIDocument<?> object = converter.readDocument(responseData, type);
```

**Comment by hndmrsh** [comment]
That looks good to me. Parsing the JSON to extract the type seems inevitable; without the `getType` helper method, the only other way to get the type information is to parse the JSON string using some other method anyway (such as using the built-in JSONObject).

**Comment by darko1002001** [comment]
But this way you are parsing the object 2 times.. which is not good. And it wont work with streams like reading directly from the network input stream. since after the first read the stream will be closed.

what might be a good idea is to do a wrapper object,

```
Wrapper wrap = converter.wrapOrSomeBetterName(responseData);
Type type = wrap.getType();
wrap.getAs(SomeClass.cls); 
wrap.getAsJsonDocument():
```
etc...
But this would require quite a rework, basically just parse the json tree into memory first and determine the types then when calling getAsJsonDocument(); create the objects.

@jasminb @hndmrsh What do you think?

**Comment by jasminb** [comment]
Simpler solution would be just adding another method that allows conversion without providing class. Since JSON is parsed before the class is needed, it is simple enough to implement it without having to touch existing code. In case type is not registered exception would be thrown. 

However, problem I have with it is that it pollutes the resource converter with a method they could be misused, but I guess that's up to the users to decide.

**Comment by darko1002001** [comment]
I've thought about this and nothing needs to be changed in the API of the library. What he wants to do should be doable with polymorphism.

```
@Type("a")
class A implements Notification {}
@Type("b")
class B implements Notification {}

JSONDocument<Notification> result = converter.readDocument(data, Notification.class);
```

Then something like the visitor pattern can be used to process it based on the concrete class.

I haven't tried it but i guess it should work. I had similar case with a relationship which was a polymorphic relationship of an object.

**Comment by hndmrsh** [comment]
@darko1002001: thanks for the suggestion, but this is not possible as abstract classes and interfaces cannot be deserialized. Even making the `Notification` class concrete does not fix the situation, as the library will not deserialize a class without a `@Type` annotation (unless I am doing something wrong).

I feel like @jasminb 's original suggestion is probably the cleanest approach here.

**Comment by darko1002001** [comment]
What have you tried to do so far? why not have classes that have a type annotation? 

The way it works is that the converter checks the registered types -> if type is "a" create new instance of A: if type is B create new instance of B > assign it to a variable of type Notification -> return it. which most definitely will work.

**Comment by hndmrsh** [comment]
Hey @darko1002001 - I understand what you're saying, and I tried implementing it exactly as you described it previously, and it did not work. `readDocument(Intent, Class)` does not allow an interface or abstract class to be passed in as the second parameter.

**Comment by darko1002001** [comment]
Then its an issue in the library, since on a nested level it works just fine.

**Comment by jasminb** [comment]
Hey @hndmrsh and @darko1002001,

I've pushed #66 , it adds support for deserialising objects using super-type as argument when invoking `readDocument` method.

This change makes it possible to have following scenario:

```
class A {};

@Type("my-subtype-one")
class B extends A {}

@Type("my-subtype-two")
class C extends A {}

A result = readDocument(data, A.class);
```

Result will be instance of class that has its `type` value equal to the value found in response.

**Comment by hndmrsh** [comment]
Hey @jasminb - I've checked out #66, and it fixes the issue for me. I think it's a nice elegant solution. Thanks!
