### ISSUE TITLE
Deserealize Links at top level

### ISSUE THREAD

**Issue by joaofyz** [jasminb/jsonapi-converter#65]
Hi,

We are using the 0.4 version of the library and also tried in the 0.5 snapshot. We tried to deserealize a collection with the Links object at top level:

`{
  "data": [
   ...
  ],
  "meta": {
    "totalResults": "2709"
  },
  "links": {
    "first": "first_link",
    "next": "next_link",
    "last": "last_link"
  }
}`

We tried to add in our resource class the @Links annotation but it's always null, I think that's because our Links object is defined at top level right?

How can we parse the Links object?

Thanks for your help

**Comment by jasminb** [comment]
Hello @joaofyz, top level meta and links are available only if new methods are used for deserialisation (namely `readDocument` and `readDocumentCollection`). These methods return `JSONAPIDocument<?>` object which wraps target type, inside this object you can find top level meta and links.

**Comment by jasminb** [comment]
Hey @joaofyz, any update on this, please let me know so we can move forward on this.

**Comment by joaofyz** [comment]
Hi @jasminb,

Thanks for your reply, we will try it tomorrow and then I give you some feedback, but I think that will solve it ;)

**Comment by joaofyz** [comment]
Hi @jasminb,

We have tested your suggestion and it worked ;)

Thanks I will close the issue
