### ISSUE TITLE
I would like to get the relationships- authors-links-self, donno how to get it , Pls help me to get the self link 

### ISSUE THREAD

**Issue by pradeepmallika** [jasminb/jsonapi-converter#67]
> {
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!",
      "body": "The shortest article. Ever.",
      "created": "2015-05-22T14:56:29.000Z",
      "updated": "2015-05-22T14:56:28.000Z"
    },
    "relationships": {
     "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
    }
  },
  "included": 
    {
      "type": "people",
      "id": "42",
      "attributes": {
        "name": "John",
        "age": 80,
        "gender": "male"
      }
    }
  }

**Comment by jasminb** [comment]
Hello,

Can you please make sure that provided result is valid JSON.

**Comment by pradeepmallika** [comment]
@jasminb   I have taken from http://jsonapi.org/examples/#error-objects-source-usage

and done small modification  in relationship part.

**Comment by jasminb** [comment]
Hello @pradeepmallika,

Library does not allow direct access for relationship links i related objects, it allows for resolving relationships by implementing and registering relationship resolver.

This is the interface that needs to be implemented:

```
public interface RelationshipResolver {
	byte [] resolve(String relationshipURL);
}
```

Purpose of the resolver is to execute fetch using the relationship URL and than deserialise the response (it works transparently).

Now if you don't want this to happen automatically but still need to know the relationship URL, you can do the following:

```
public class MyCustomRelationshipResolver implements RelationshipResolver {
	private String relationshipURL;

	public  byte [] resolve(String relationshipURL) {
		this.relationshipURL = relationshipURL;
		return null;
	}

	public String getRelationshipURL() {
		return relationshipURL;
	}
}

```

Now, when you create your resource converter, do the following:

```
ResourceConverter converter = new ResourceConverter(...);

MyCustomRelationshipResolver customResolver = new MyCustomRelationshipResolver();
converter.setTypeResolver(customResolver, yourRelationshipTypeClass);

```

Now, after you execute a request, you will be able to get the relationship URL from the resolver by:

```
String url = customResolver.getRelationshipURL();
```

Please have in mind that this is a `hack` solution, proper solution would be to implement actual relationship resolver and use it to dereference linked relationships.

**Comment by pradeepmallika** [comment]
@jasminb  Thanks for your response ,I am using Retrofit , whether your solution can be used with Retrofit ?

**Comment by jasminb** [comment]
Sure it can, you need to create an instance of `ResourceConverter` to use it with retrofit, when you create it, you need to register type resolver with it.

**Comment by pradeepmallika** [comment]
@jasminb  you email-id pls ?

**Comment by jasminb** [comment]
Hey @pradeepmallika, I would prefer to keep the discussion on this thread. If you need to share something you are not comfortable with sharing, you can change it in a way it does not expose any of your specifics and share it.

**Comment by pradeepmallika** [comment]
@jasminb  We are using   JSONAPIConverterFactory only, in JSONAPIConverterFactory where i can create instance of ResourceConverter ? an working example will be help full.

**Comment by jasminb** [comment]
Hey @pradeepmallika, if you check https://github.com/jasminb/jsonapi-converter/blob/develop/src/main/java/com/github/jasminb/jsonapi/retrofit/JSONAPIConverterFactory.java, you can see that there are two different constructors that take `ResourceConverter` as arguments.

**Comment by pradeepmallika** [comment]
@jasminb I tired many ways , it is not working,an simple example with below given jason will be useful , thanks in advance.

> {
"data": {
"type": "articles",
"id": "1",
"attributes": {
"title": "JSON API paints my bikeshed!",
"body": "The shortest article. Ever.",
"created": "2015-05-22T14:56:29.000Z",
"updated": "2015-05-22T14:56:28.000Z"
},
"relationships": {
"author": {
"links": {
"self": "http://example.com/articles/1/relationships/author",
"related": "http://example.com/articles/1/author"
},
}
},
"included": 
{
"type": "people",
"id": "42",
"attributes": {
"name": "John",
"age": 80,
"gender": "male"
}
}
}

**Comment by jasminb** [comment]
Hey @pradeepmallika, in this example the `included` section is not relevant since there is no type/id information in `author` relationship object. I can provide detailed example on how to get the relationship links if thats what you need.

**Comment by pradeepmallika** [comment]
@jasminb here is my response replica,Pls provide an example to get relationships- authors-links , I  am getting the response through retrofit 

> 

	
	{
	    "data": {
	        "type": "supermarket",
	        "id": "mal2313213223123123",
	        "attributes": {
	            "created_time": "Aug 29",
	            "modified_time": "Aug 29",
	            "name": "testingsupermarket123",
	            "description": "TestingDesc",
	        },
	        "relationships": {
	            "provisionsdepartment": {
	                "links": {
	                    "self": "https://testingsupermarket.com/supermarket/api/mal2313213223123123/relationships/provisionsdepartment",
	                    "related": "https://testingsupermarket.com/supermarket/api/mal2313213223123123/provisionsdepartment"
	                }
	            },
	            "permissions": {
	                "links": {
	                    "self": "https://testingsupermarket.com/supermarket/api/mal2313213223123123/relationships/permissions",
	                    "related": "https://testingsupermarket.com/supermarket/api/mal2313213223123123/permissions"
	                }
	            },
	            "authors": {
	                "links": {
	                    "self": "https://testingsupermarket.com/supermarket/api/mal2313213223123123/relationships/authors",
	                    "related": "https://testingsupermarket.com/supermarket/api/mal2313213223123123/authors"
	                }
	            },
	            "emplist": {
	                "links": {
	                    "self": "https://testingsupermarket.com/supermarket/api/mal2313213223123123/relationships/emplist",
	                    "related": "https://testingsupermarket.com/supermarket/api/mal2313213223123123/emplist"
	                }
	            }
	        },
	        "links": {
	            "self": "https://testingsupermarket.com/supermarket/api/mal2313213223123123"
	        }
	    },
	    "included": []
	}

**Comment by jasminb** [comment]
Hey @pradeepmallika, do you still need this?

**Comment by pradeepmallika** [comment]
@jasminb No, I found the way to get relationship url, but one question Whether Jsonapi-convertor provides and support to  to consume the resource link in order to fetch actual resources from the server. , or i need to done it my self with http get request or through Retrofit.

**Comment by pradeepmallika** [comment]
@jasminb   No ,thank you 👍
