### ISSUE TITLE
Creating objects is impossible

### ISSUE THREAD

**Issue by huberts** [jasminb/jsonapi-converter#71]
Hello!

Is there a way to parse a newly created object from client-side? Such object does not have an ID and according to JSON API it should be considered as a new one: http://jsonapi.org/format/#document-resource-objects.

**Comment by huberts** [comment]
Ok, I found the solution, you only need to disable one option in your converter:
`converter.disableDeserializationOption(DeserializationFeature.REQUIRE_RESOURCE_ID)`
If this is the proper way to go, I am satisfied :-)

**Comment by jasminb** [comment]
Hey, yes that would be the way to do it.
