### ISSUE TITLE
NullPointerException while trying to serialize a (fetch = FetchType.LAZY) attribute

### ISSUE THREAD

**Issue by dodos90** [jasminb/jsonapi-converter#73]
Hello,

First of all, I'd like to thank the author(s) of this lib for their great work, it is really helpful.
I'm encountering an issue with the serialization of an object managed by Hibernate (server-side), with some attributes annotated with `@ManyToOne(fetch = FetchType.LAZY)`.

When I try to serialize those attributes, I get a `NullPointerException` : 

`java.lang.NullPointerException
    at com.github.jasminb.jsonapi.ResourceConverter.getDataNode(ResourceConverter.java:684)
    at com.github.jasminb.jsonapi.ResourceConverter.getDataNode(ResourceConverter.java:672)
    at com.github.jasminb.jsonapi.ResourceConverter.writeDocument(ResourceConverter.java:566)`

From the debugger view, it seems that the managed attribute is not fully initialized by Hibernate (thus, the ID is null and cannot be serialized by Jackson), but the proxy object is fully initialized (I can see all the values of the attributes I want from the debugger view).

Do you have any ideas how I could force the initialization of the object before the serialization ?

Thanks a lot !

Adrien.

**Comment by jasminb** [comment]
Hey,

You can try this:


```
  public static <T> T init(T model) {
    if (model == null) {
      return null;
    }

    Hibernate.initialize(model);
    if (model instanceof HibernateProxy) {
      model = (T) ((HibernateProxy) model).getHibernateLazyInitializer()
          .getImplementation();
    }
    return model;
  }
```

**Comment by jasminb** [comment]
Closed as unrelated to the lib itself but rather to library used to fetch data from DB.
