### ISSUE TITLE
Is it possible to serialize a resource and its links with jsonapi-converter ?

### ISSUE THREAD

**Issue by dodos90** [jasminb/jsonapi-converter#74]
Hi,

I'm trying to use this library to serialize some resources from server-side, before sending them to my client.

I've got a `UserObject` that looks like this : 

`public class UserObject {
    @com.github.jasminb.jsonapi.annotations.Id
    @JsonIgnore
    private String stringId;

```
@com.github.jasminb.jsonapi.annotations.Links
protected Links links;

@Relationship("userDeviceMap")
private List<UserDeviceMap> userDeviceMap = new ArrayList<>();

// Getters and setters`
```

My `UserDeviceMap` looks like this : 

`public class UserDeviceMap {

```
@Relationship(value = "user")
private UserObject user;

@com.github.jasminb.jsonapi.annotations.Links
protected Links links;

// Getters, setters and some other stuff`
```

If I serialize those resources with `SerializationFeature.INCLUDE_LINKS` enabled, I can't see any links. Seems fair. But if I create manually a link, either in `UserDeviceMap` or in `UserObject`, it is serialized in the "data" block : 

`"data":{  
      "links":{  
         "self":{  
            "href":"http://www.myprojecturl.com/api/users/4000"
         }
      },
      "type":"user",
      "id":"4000"
}
....
`

I would like to see the links in the "relationships" block, as seen in the JSON API doc : 

`"relationships": {
      "author": {
        "links": {
          // THE LINKS ARE IN THE RELATIONSHIPS BLOCK
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      }...
`

Is it possible to do so with this library ? And if it is, how can I achieve this ?

Thanks a lot !

Adrien.

**Comment by jasminb** [comment]
Hey,

Currently lib will include relationship object's links in the data section. So if you enable `SerializationFeature.INCLUDE_RELATIONSHIP_ATTRIBUTES`, `incldued` section will be present that will contain the link data.

I will make necessary changes in order to make links available trough the `relationship` object even if `SerializationFeature.INCLUDE_RELATIONSHIP_ATTRIBUTES` is disabled.

**Comment by hvgotcodes** [comment]
@jasminb 

Any update on when this will land?  Thanx.

**Comment by jasminb** [comment]
Issue was fixed and pushed to develop. In order to use it, use the snapshot version of the library (release will be made in next few days).

Example model and mapping:

```java
@Type("statuses")
public class Status {
	@Id
	private String id;

	@Relationship(value = "user",)
	private User user;

	@RelationshipLinks("user")
	private Links userRelationshipLinks;
```

Links attribute will be both serialised and deserialised correctly.

**Comment by hvgotcodes** [comment]
Is this supposed to work with relationships that are Lists?  Im not getting the link in the OP still.

**Comment by jasminb** [comment]
It will work for both collection and single object relationship types.

Please note that annotation is added on the owning side of the relationship.

**Comment by hvgotcodes** [comment]
Hmm I've done this

@Relationship(value="things")
    public List<Thing> things;

    @RelationshipLinks("things")
    private Links thingsRelationshipLinks;

And I'm not seeing the link the json.

Thank you for the prompt attention, btw.

**Comment by hvgotcodes** [comment]
Hold off for a bit, I think I screwed up getting the snapshot.

**Comment by jasminb** [comment]
One more note, `List<Thing> things` cannot be `null`, if relationship is null, links will be skipped.

**Comment by hvgotcodes** [comment]
I was going to get to that. :)  Can the list be empty, and will the links be written?  Seems that is a valid case.

**Comment by jasminb** [comment]
Empty is fine.

**Comment by hvgotcodes** [comment]
Ok, I do have the right jar.  In the `getRelationshipLinks` method this line

```
Object links = relationshipLinksField.get(source);
```
is returning null, for the relationship I described.

**Comment by jasminb** [comment]
Can you paste serialised content here, if the line you pasted returns null than links object (if actually not null) will be present as an regular attribute.

**Comment by hvgotcodes** [comment]
I'm not sure what you are asking for.  The serialized json looks like

```
      "relationships" : {
         "things" : {
            "data" : [
               {
                  "type" : "things",
                  "id" : "..."
               },
               {
                  "id" : "....",
                  "type" : "things"
               }
            ]
         },
```

What is the links object you speak of?

**Comment by jasminb** [comment]
So assuming your `root` class is named `Root`:

```java
@Type("root")
public class Root {
...
@Relationship(value="things")
public List<Thing> things;

@RelationshipLinks("things")
private Links thingsRelationshipLinks;
}

# Create root
Root root = new Root();
root.things = new List();
root.thingsRelationshipLinks = new Links(new HashMap<String, Link>);

converter.writeDocument(new JSONAPIDocument(root));

```

**Comment by hvgotcodes** [comment]
Yes this is the problem, I have to populate the links.  I wonder if the framework should be able to construct the url though.

**Comment by jasminb** [comment]
Its a good idea, I will consider it. It would be simple enough to extend current type/relationship annotations so one can provide uri related details, eg.

```java
@Type("root", uri="/api/v1/roots/{id}"

@Relationship("things", uri="/things")
```

In the mean/time, you can construct it yourself as a workaround.

**Comment by hvgotcodes** [comment]
Yes working on that now.   Again, appreciate the prompt replies.

**Comment by jasminb** [comment]
Sure thing.
