### ISSUE TITLE
Can not deserialise json to object model when there is no default constructor

### ISSUE THREAD

**Issue by thinh76** [jasminb/jsonapi-converter#75]
`
@Type("Person")
class Person {
  @Id
  private String id;

 @JsonCreator
  public Person(@JsonProperty("id") String id) {
     this.id = id;
  }

  public String getId() {
    return id;
  }
}

new ResourceConverter.readObject("\n"
        + "{\n"
        + "   \"data\": {\n"
        + "      \"id\": \"1\",\n"
        + "      \"type\": \"Type\"\n"
        + "      \n"
        + "   }\n"
        + "}", Person.class) `
will fail with InstantiationException.. 
I am wondering if we could make this work without having to have a default constructor ?

**Comment by jasminb** [comment]
Hey,

Having default constructor is the norm for any type of deserialisation. One could consider implementing support for object factories, however having default ctor is simplest solution.

**Comment by thinh76** [comment]
Yeah, I agree. It's just that with ObjectMapper it supports @JsonCreator annotation which removes the need for having default constructor. And I am actually looking at this library and wrap it around with Scala, and in Scala case classes, having a default constructor defeats the immutability purpose.. I think the fix for it would just be changing result = clazz.newInstance() in the following block to if (result == null) {
			if (source.has(ATTRIBUTES)) {
				result = objectMapper.treeToValue(source.get(ATTRIBUTES), clazz);
			} else {
				if (clazz.isInterface()) {
					result = null;
				} else {
					result = clazz.newInstance();
				}
			} to result = objectMapper.treeToValue(objectMapper.createObjectNode(), clazz);
What do you think?

**Comment by jasminb** [comment]
Hey @thinh76, I've taken your suggestion and pushed to develop. It should be available in `SNAPSHOT` version.

**Comment by thinh76** [comment]
Hi @jasminb, thank you so much.... any idea when this SNAPSHOT will be released? 

Thanks heaps again.

**Comment by jasminb** [comment]
Hey, I've deployed latest develop to sonatype snapshot repo.

**Comment by thinh76** [comment]
thanks @jasminb. Are you in a position to release 0.5?
