### ISSUE TITLE
After taking the relationship url using RelationResolver , whether it is possible to do http request with that url (through retrofit) and get the response ? 

### ISSUE THREAD

**Issue by pradeepmallika** [jasminb/jsonapi-converter#76]

**Comment by jasminb** [comment]
Hey, would be lovely if you could provide more details. Are you asking for a way to consume the resource link in order to fetch actual resources from the server?

**Comment by emetsger** [comment]
You can use the @Url parameter annotation, which allows you to use the full
url obtained from @Relationship.

There are a few methods on this example Retrofit service that use this
approach:
https://github.com/emetsger/osf-client/blob/master/src/main/java/org/dataconservancy/cos/osf/client/service/OsfService.java

**Comment by pradeepmallika** [comment]
@jasminb  yes,I want the way to consume the resource link in order to fetch actual resources from the server.

**Comment by jasminb** [comment]
Hey @pradeepmallika, please check the link that @emetsger provided, it has an example method in the retrofit service that will do exactly what you need.
