### ISSUE TITLE
Q: Deserialising array of different type objects?

### ISSUE THREAD

**Issue by markoilicic** [jasminb/jsonapi-converter#77]
Hi Jasmin,

I'm trying to implement your library, but I'm not able to figure out how it's possible to define parsing  data with array of different types. E.g.:

```
{
  "data": [
    {
      "id": "1",
      "type": "foo",
      "attributes": {
        "name": "Foo"
      },
      "relationships":{
      }
    },
    {
      "id": "1",
      "type": "bar",
      "attributes": {
        "name": "bar"
      },
      "relationships":{
      }
    }
  ]
}
```

Is that possible with your library and how? 
Thanks for answer in front...

**Comment by jasminb** [comment]
Hey @markoilicic,

It is not possible to have objects of different type in one resource array.

I've checked the spec and was not able to find if it was allowed or not.

**Comment by markoilicic** [comment]
Thanks for fast response!

I was also checking spec, but there is no info about that case. My API have that structure, and I'm not sure if that is allowed or not... :)

**Comment by jasminb** [comment]
Hey,

My opinion is that there should not be an API method that returns collection of different elements as a result. It is a bad practice and generally makes it really hard for the users to consume it.

I'm not sure if you are owning the API backend side or not, if you do, change it :)

Regards

**Comment by jasminb** [comment]
Hey @markoilicic, if you create a class that both `foo` and `bar` extend, you should be able to pull it off.

**Comment by markoilicic** [comment]
Hej @jasminb, thx for pointing that out. 
We (my college) have realized that yesterday on this commit: https://github.com/jasminb/jsonapi-converter/commit/e0e6854932e6e8e958aad6e46b64a09d71e0f834

I was just about to let you know that there is the way for parse it that way.

I believe that I just need to add any `@Type` annotation to the base class (or the one that is used as superType) to make it work. E.g.:

```
@Type("base")
abstract class BaseResource {
    @Id
    protected String id;

    abstract ItemType getType();
}

abstract class BaseResource {
        @Id
        protected String id;

        abstract ItemType getType();
    }

    @Type("foo")
    public class Foo extends BaseResource {
        private String name;

        @Override
        ItemType getType() {
            return ItemType.FOO;
        }
    }

    @Type("bar")
    public class Bar extends BaseResource {
        private String title;

        @Override
        ItemType getType() {
            return ItemType.BAR;
        }
    }
```

so I can use `JSONAPIDocument<List<BaseResource>>` and simply check the type... this works like a charm :)

Maybe you could add some example for this case in the README, since I can see that other people also are not aware of how to accomplish that...

BTW - Good job :)

**Comment by jasminb** [comment]
Glad you find the lib useful. Will update the README with the example for this use-case, thanks for pointing it out.

**Comment by ericn37** [comment]
Does this work with Retrofit guys?
What is `ItemType` @markoilicic ?

**Comment by markoilicic** [comment]
@ericn37 yes, I'm using it with retrofit 2 and it works great... ItemType is just an enum which I use to identify the object type... you can use the same string which is used in @Type annotation...

@jasminb is it possible to make some public method for fetching Type that is used in @Type?

**Comment by ericn37** [comment]
Hi @markoilicic, could you help to shed some more light on your implementation please as I'm having problem achieving it?

Problem
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.yyy/com.sephora.digital.views.activities.MyActivity}: java.lang.IllegalArgumentException: Unable to create converter for com.github.jasminb.jsonapi.JSONAPIDocument<com.sephora.digital.models.BaseResource
...
```
Model:
```
@JsonIgnoreProperties(ignoreUnknown = true)
@Type("mytype")
public class MyModel extends BaseResource {
    @JsonProperty("slug-url")
    private String slug;
}
```
Base Model:
```
@JsonIgnoreProperties(ignoreUnknown = true)
@Type("basesourcetype")
public abstract class BaseResource {
    @Id
    protected String id;
}
```
Retrofit stuffs:
MyRESTClient.java
```
public static JSONAPIConverterFactory converterFactoryJasminb = new JSONAPIConverterFactory(converterJasminb);
    public static final Retrofit retrofitJasminb = new Retrofit.Builder()
            .baseUrl(STAGING)
            .client(getOkHttpClient())
            .addConverterFactory(converterFactoryJasminb)
            .build();
// I don't include BaseResource here coz it's abstract
public static ResourceConverter converterJasminb = new ResourceConverter(
            MyModel.class
);
```
MyService.java
```
public interface MyService {

    MyService service = MyRESTClient.retrofitJasminb.create(MyService.class);

    @GET("base/{objectId}")
    Call<JSONAPIDocument<BaseResource>> fetchTheObject(@Path("objectId") String objectId);
}
```

**Comment by markoilicic** [comment]
@ericn37 you must add the BaseResource.class to the ResourceConverter too..

**Comment by ericn37** [comment]
Hi @markoilicic , in the case `BaseResource` cannot be `abstract`, can it?

**Comment by markoilicic** [comment]
@ericn37 I'm using it as an abstract class, just like it's shown on the given example above with the Foo & Bar classes...

I create retrofit a little bit different:
```
retrofit = new Retrofit.Builder()
                .client(client)
                .baseUrl(baseUrl)
                .addConverterFactory(new JSONAPIConverterFactory(new ObjectMapper(),
                        BaseResource.class,
                        Foo.class,
                        Bar.class))
                .build();
```

**Comment by ericn37** [comment]
Actually, I think it doesn't really matter if `BaseResource` is abstract or not.
I won't be able to cast `BaseResource` to `MyModel` anyway.

How do you use Retrofit @markoilicic would you mind sharing a snippet of your code?

**Comment by markoilicic** [comment]
@ericn37 why you can't cast `BaseResource` to the `MyModel`? It's working fine for me...

Retrofit interface should look like:
```
@GET("path")
Call<JSONAPIDocument<List<BaseResource>>> getResources();
```

Or if you are using RxJava
```
@GET("path")
Observable<JSONAPIDocument<List<BaseResource>>> getResources();
```

I simply check the type of the BaseResource and cast it to right model, 
e.g.:
```
if(baseResource.getItemType().equals(ItemType.FOO){
    return (Foo) baseResource;
}
```

If you debug response, you will see in the list that objects are properly parsed...

**Comment by ericn37** [comment]
Hi @markoilicic , I've debugged and the object I got after after de-serialised the JSON response from the server is a `BaseResource` object, not `MyModel` or anything else.
Hence the `ClassCastException`.

**Comment by markoilicic** [comment]
@ericn37 are you using SNAPSHOT or 0.4 version? I'm working with snapshot-0.5 since I have noticed that that is added after 0.4 version in mentioned commit...

**Comment by ericn37** [comment]
I'm using 0.5 version @markoilicic :)

**Comment by markoilicic** [comment]
@ericn37 well.. :)
can you give snippets of your objects and how does response looks like?

**Comment by ericn37** [comment]
Hi @markoilicic , 
One response (type A) looks like this:
```
{
    "data": {
        "id": "2222",
        "type": "landing-pages-defaults",
        "attributes": {
            "slug-url": "default-test-app",
            "layout": "default",
            "banner-image": "",
            "banner-alt-text": "",
            "banner-link": "",
            "banner-video-id": "",
            "product-box-title": ""
        }
    }
}
```

And the other (type B):
```
{
    "data": {
        "id": "2219",
        "type": "landing-pages-promo-list-twos",
        "attributes": {
            "slug-url": "promo-list-2-test",
            "layout": "promo_list_2",
            "mobile-banner-image-url": null
        }
    }
}
```

**Comment by markoilicic** [comment]
@ericn37 
add this to your app level `build.gradle`

```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }
}

dependencies {
    compile 'com.github.jasminb:jsonapi-converter:0.5-SNAPSHOT'
}
```

can you provide model classes too? for the BaseModel, and both that comes into the response?

**Comment by ericn37** [comment]
it works as of version 0.5 @markoilicic @jasminb 
Thanks a lot guys!

**Comment by jasminb** [comment]
Hey @ericn37,

Glad you got it working..

**Comment by returnt** [comment]
How to parse an array of this type

`{
"data": [
{
"type": "likes",
"id": "69",
"attributes": {
"user": 1,
"post": 250
},
"relationships": {
"user": {
"data": {
"id": "1",
"type": "users"
}
}
}
},
{
"type": "likes",
"id": "68",
"attributes": {
"user": 3,
"post": null
},
"relationships": {
"user": {
"data": {
"id": "3",
"type": "users"
}
}
}
}`
