### ISSUE TITLE
Consider supporting @Id for int/long fields?

### ISSUE THREAD

**Issue by tbilsborrow** [jasminb/jsonapi-converter#80]
It might be nice to be able to annotate an int or long field to use as the Id, and convert automatically to/from String upon serialization/deserialization (with an error if it is not possible to convert from a String in a json document to a number in a model class). I can submit a PR, but first wanted to check if there is fundamental opposition to the idea.

**Comment by jasminb** [comment]
Hey @tbilsborrow,

There is no reason not to as long as its serialised as `String` and converted properly back to whatever type user annotated with `@Id`.

It will make things interesting since lib than has to support `String -> whatever type` conversion for the id field.

**Comment by jasminb** [comment]
Hey @tbilsborrow,

Support for non-string resource identifiers has been added in 2a06cc2f6bd5c6efed3f0f3ff2516785bc3474aa. 

`@Id` annotation was extended with optional argument which if provided overrides default identifier handling.
New interface has been provided that needs to be implemented for custom type handling (`ResourceIdHandler`).

Besides providing default `String` handler, lib also provides handlers for `Long` and `Integer` (`LongIdHandler` and `IntegerIdHandler`).

Sample class using `Long` as id:

```java
@Type("long-id-type")
public class LongIdResource {
	
	@Id(LongIdHandler.class)
	private Long id;
// ...
}
```
