### ISSUE TITLE
Consider supporting serialization of collection as primary data

### ISSUE THREAD

**Issue by nikolafon** [jasminb/jsonapi-converter#81]
When you pass collection as a data you will get 
`java.lang.ClassCastException: com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode`.
Primary data by JSON API specification can be array as well.
Please consider supporting it.

**Comment by jasminb** [comment]
Hey @nikolafon, do you mind providing actual data here?

**Comment by nikolafon** [comment]
Data is not of relevance. If you pass any collection of test objects you should get this error.
The conversion is the problem.
`
// Perform initial conversion
ObjectNode attributesNode = objectMapper.valueToTree(object);
`
method valueToTree(object) returns <T extends JsonNode> but ObjectNode is always expected.

**Comment by jasminb** [comment]
JSONAPI Specification allows for collections but in a following way:

```
{
  "data": [
    {
      "type": "articles",
      "id": "1",
      "attributes": {
        "title": "JSON API paints my bikeshed!"
      }
    },
    {
      "type": "articles",
      "id": "2",
      "attributes": {
        "title": "JSON API paints my bikeshed!"
      }
    },
    {
      "type": "articles",
      "id": "3",
      "attributes": {
        "title": "JSON API paints my bikeshed!"
      }
    }
  ]
}
```

And not not like:

```
[
  {
    "data": {
      "type": "articles",
      "id": "1",
      "attributes": {
        "title": "JSON API paints my bikeshed!"
      }
    }
  },
  {
    "data": {
      "type": "articles",
      "id": "2",
      "attributes": {
        "title": "JSON API paints my bikeshed!"
      }
    }
  },
  {
    "data": {
      "type": "articles",
      "id": "3",
      "attributes": {
        "title": "JSON API paints my bikeshed!"
      }
    }
  }
]
```

**Comment by nikolafon** [comment]
I'm trying to create `JSONAPIDocument` with a collection passed as primary data to constructor.
I mean to serialize to JSON not from JSON to a `JSONAPIDocument`.
Am i doing something wrong?

**Comment by jasminb** [comment]
Hey @nikolafon,

There is: 

```
writeObjectCollection(Iterable<T> objects) {}
```

Have in mind that it was not upgraded to new API where JSONAPIDocument<> is used, but it should work for what you need.

**Comment by nikolafon** [comment]
The reason I asked for collection serialization support is exactly that method.
Yes, there is option to use `writeObjectCollection(Iterable<T> objects) {}` but that method doesn't write "links" and "meta" to the root of the json api document which is also allowed by the standard.
Thank you for your answers.

**Comment by jasminb** [comment]
Hey, I will add the new method that complies with the other ones that consume the JSONAPIDocument, it will support top level links/meta as all other methods do.

**Comment by nikolafon** [comment]
Awesome. Thanks.

**Comment by jasminb** [comment]
Hey @nikolafon, Ive pushed a new method we discussed about. Please make sure to use `0.5-SNAPSHOT` version since new release will take few more days.

**Comment by jasminb** [comment]
@nikolafon, 0.5 was released few days ago. Please give it a try and close the issue if it works out for you.

**Comment by nikolafon** [comment]
@jasminb Thank you for the effort. I didn't have time to take a look at it but I plan soon. We had different priorities. I will get back to u you.

**Comment by nikolafon** [comment]
@jasminb Thank you for the effort. I didn't have time to take a look at it but I plan soon. We had different priorities. I will get back to u you.

**Comment by nikolafon** [comment]
@jasminb I checked the version 0.5. It works as expected.
I'm closing the issue now.
