### ISSUE TITLE
NullPointerException when serializing  JSONAPIDocument and "primary data" is empty

### ISSUE THREAD

**Issue by nikolafon** [jasminb/jsonapi-converter#82]
`ResourceCoverter` currently expects that data is always set in order for document to be serialized from Java objects to JSON. 
Spec says: 
"A document MUST contain at least one of the following top-level members: 
data: the document’s “primary data”
errors: an array of error objects
meta: a meta object that contains non-standard meta-information."
If data is empty `NullPointerException` is thrown.

**Comment by jasminb** [comment]
This was fixed with https://github.com/jasminb/jsonapi-converter/commit/3eca3b9f71813b639d68cd9623f8fa9351cf89fb
