### ISSUE TITLE
Q: Unable to get 0.6-SNAPSHOT from sonatype?

### ISSUE THREAD

**Issue by markoilicic** [jasminb/jsonapi-converter#84]
Hi @jasminb,
I'm not able to get snapshot version from sonatype.org.
When I go to the https://oss.sonatype.org/content/repositories/snapshots/com/github/jasminb/ there is just an empty directory. Do you maybe now the reason for that?

I need that version for collection serialisation support :)

Thx

**Comment by jasminb** [comment]
Hey, use 0.5 release instead.

**Comment by markoilicic** [comment]
@jasminb I tried, but I get same error `java.lang.ClassCastException: com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode` like in the this issue.. https://github.com/jasminb/jsonapi-converter/issues/81

I thought that this commit fixes that issue: https://github.com/jasminb/jsonapi-converter/commit/ca4257a9ecdff69c5bfc9156bf7641f4afeabeff

I'm trying to send something like this as `@Body` with retrofit:

```
JSONAPIDocument<List<BaseResource>>
```
I'm creating document by constructor `new JSONAPIDocument<>(baseResources)`, but it throws me mentioned exception

Am I missing something?

**Comment by jasminb** [comment]
Hey,

There is a problem with `JSONAPIRequestBodyConverter`, will fix it and push to `develop`, will make the snapshot release also and update you here.

**Comment by markoilicic** [comment]
@jasminb Man, you are awesome :)

Thank you very much on your fast actions... Do you have a PayPal maybe? I would like to buy you a beer ;)
