### ISSUE TITLE
JSONAPIDocument missing ObjectMapper if data is `null`

### ISSUE THREAD

**Issue by markoilicic** [jasminb/jsonapi-converter#87]
Hi @jasminb,

I have the case where I only get some `meta` and `data`is `null`. In that case I'm not able to extract `meta` with `JSONAPIDocument.getMeta(Class<?> metaType)` because `private ObjectMapper deserializer;` is `null`..

When `data` is `null` document is created by the default constructor `public JSONAPIDocument()` and `ObjectMapper` is not provided... 

Is this intentionally and is my response invalid because of the null data, or this could be fixed by your side by always providing `ObjectMapper`?

**Comment by jasminb** [comment]
Hey @markoilicic,

It is a bug. Will fix it.
