### ISSUE TITLE
Meta information

### ISSUE THREAD

**Issue by fabricehong** [jasminb/jsonapi-converter#9]
Hi

Are you planning to implement the parsing of the meta information node ?

http://jsonapi.org/format/#document-meta

thanks

**Comment by fabricehong** [comment]
Hi Jasmin. I need to deliver this today. I will do it and make you a pull request if you want

**Comment by jasminb** [comment]
Hey,

I was planning to add support for meta over the weekend.
You are more than welcome to create a pull request wit the future added.

Regards,
Jasmin

**Comment by fabricehong** [comment]
Alight, I made a pull request ! please read the comment of the PR
