### ISSUE TITLE
Better Documentation for Relationship Links

### ISSUE THREAD

**Issue by hvgotcodes** [jasminb/jsonapi-converter#91]
I'm not seeing in the documentation how to get this library to output links in the relationships part of the json.  I see other issues indicating it's working; I just cant figure out how to get the links to output.  

In my class I've done the following
```
@Relationship(value="things", resolve=true, relType = RelType.RELATED)
    public List<Thing> things;
```

but the resulting json-api only has data for this relationship, no links.  

Any guidance?  Thank you in advance.

**Comment by jasminb** [comment]
Issue was fixed and pushed to develop. In order to use it, use the snapshot version of the library (release will be made in next few days).

Example model and mapping:

```java
@Type("statuses")
public class Status {
	@Id
	private String id;

	@Relationship(value = "user",)
	private User user;

	@RelationshipLinks("user")
	private Links userRelationshipLinks;
```

Links attribute will be both serialised and deserialised correctly.
