### ISSUE TITLE
Enhance Relationship Links Annotations

### ISSUE THREAD

**Issue by hvgotcodes** [jasminb/jsonapi-converter#93]
As a reminder, from [here](https://github.com/jasminb/jsonapi-converter/issues/74).

It would be simple enough to extend current type/relationship annotations so one can provide uri related details, eg.

@Type("root", uri="/api/v1/roots/{id}"

@Relationship("things", uri="/things")

**Comment by jasminb** [comment]
Implemented and pushed to develop.
