### ISSUE TITLE
Q: Get JSONAPIDocument as json string?

### ISSUE THREAD

**Issue by markoilicic** [jasminb/jsonapi-converter#95]
Hi @jasminb ,

is there a way to easily convert JSONAPIDocument to Json string? I need to get body as string before adding it to the request as `@Body`.. 

Thx in advance  and sry if I have overseen some easy solution :D

**Comment by jasminb** [comment]
Hey,

```java
new String(converter.writeDocument(document, StandardCharsets.UTF-8);
```

We could add new methods that return `String` directly but, why bother.

**Comment by markoilicic** [comment]
Thx a lot!
