### ISSUE TITLE
How to include just certain relationships in serialized json-api?

### ISSUE THREAD

**Issue by hvgotcodes** [jasminb/jsonapi-converter#96]
From the documentation, I think user can tell the library to add an `included` section to output json-api by add the `INCLUDE_RELATIONSHIP_ATTRIBUTES` feature to the `ResourceConverter`. 

What if a model has a bunch of relationships, but you only want to have one in the `included` section of the json-api, and perhaps output the other relationships solely as links.

**Comment by jasminb** [comment]
Hey,

Currently not possible. You either have them all or none. Its easy to fix tho, will make a commit in next few days and update you here.

**Comment by hvgotcodes** [comment]
Cool.   Thank you for being so responsive.  As you know, Json-API is more than just a json format -- it specifies how clients should be able to request data from a server.  So sometimes we might want to load an object with no includes, and sometimes we might want to include only certain relationships.  Being able to specify that on a per-serialization basis would be helpful.

**Comment by fatonarifi** [comment]
Hi @jasminb,

It would be great if we have this solution for the next few days, you are going to be my hero :).

Thanks a lot.

**Comment by jasminb** [comment]
Hey @fatonarifi, its work in progress, will happen very soon.

**Comment by Alexander-Krause** [comment]
Hi @jasminb, this is possible when reading or writing. But can I save this in a ResourceConverter instance as well?
