### ISSUE TITLE
[Discussion] Allow unknow type in includes

### ISSUE THREAD

**Issue by Kevinrob** [jasminb/jsonapi-converter#99]
First, thank for this library!

I run into an issue where:
- I call a PATH with some includes of different type
- In the includes, there is a new type (not registered in my app)
- Exception throw at https://github.com/jasminb/jsonapi-converter/blob/develop/src/main/java/com/github/jasminb/jsonapi/ResourceConverter.java#L398

I think that it can be good that the converter allow (and support) an unknown type in included items. Because it's normal that the application must know the type of the `data`, but not for includes.

Maybe new objects (== new type) can be added to the API and the application have to handle this without crashing. No?

**Comment by Kevinrob** [comment]
For illustration, I have do it with an old version of this library (0.5 I think):
https://github.com/Kevinrob/jsonapi-converter/commit/8fb734f9679dc52de21098f5ae94a15a59a93600
https://github.com/Kevinrob/jsonapi-converter/commit/f42905dd5ae6109f22806a8d29e9a7d1134c2a68

**Comment by jasminb** [comment]
Hello @Kevinrob,

One way to do it would be to add global deserialisation option that allows for unknown type(s) on included documents.

Will add it in next few days and update you here.

Thanks for reporting.

**Comment by tklovett** [comment]
Hey @jasminb, I went ahead and created a PR for this, I hope I captured what you were envisioning for this feature. Please let me know if you want me to change any formatting/commenting/testing/behavior or anything.

**Comment by jasminb** [comment]
Resolved in `develop`, use snapshot version for testing.

**Comment by tklovett** [comment]
What's the schedule for releasing a new version with this commit?

Thomas Lovett
tklovett@gmail.com

sent via mobile
